import React, { createContext, useContext, useState, useEffect } from 'react';
import { settingsService } from '../services/settingsService';

const translations = {
  pt: {
    // Tabs
    home: 'Início',
    songs: 'Músicas',
    setlists: 'Setlists',
    about: 'Sobre',
    
    // Home Tab
    myBands: 'Minhas Bandas',
    quickStats: 'ESTATÍSTICAS RÁPIDAS',
    totalSongs: 'Total de Músicas',
    totalSetlists: 'Total de Setlists',
    noBands: 'Nenhuma banda cadastrada ainda. Clique em "+ Banda" no topo para criar!',
    noSongs: 'Nenhuma música encontrada. Clique em "+ Música" no topo para cadastrar!',
    upcomingEvents: 'PRÓXIMOS EVENTOS',
    
    // Song / Band / Setlist Actions
    edit: 'Editar',
    delete: 'Excluir',
    copy: 'Duplicar',
    share: 'Compartilhar',
    exportWord: 'Exportar Word',
    startStage: 'Palco',
    addBand: '+ BANDA',
    addSong: '+ MÚSICA',
    addSetlist: '+ SETLIST',
    importBtnText: '📥 IMPORTAR',
    searchPlaceholderDesc: 'Buscar por título, artista ou estilo...',
    
    // Settings / Theme Modal
    themeAppearance: 'TEMA E APARÊNCIA',
    themeMode: 'MODO DO TEMA',
    dark: 'Escuro 🌙',
    light: 'Claro ☀️',
    primaryColor: 'COR PRIMÁRIA',
    secondaryColor: 'COR SECUNDÁRIA',
    appLanguage: 'IDIOMA DO APLICATIVO',
    save: 'SALVAR CONFIGURAÇÕES',
    cancel: 'Cancelar',
    optionsBtn: 'Opções',
    optionsTitle: 'Opções',
    closeBtn: 'FECHAR',
    
    // Band Modal
    newBand: 'NOVA BANDA',
    editBand: 'EDITAR BANDA',
    bandNameLabel: 'NOME DA BANDA *',
    coverImageLabel: 'FOTO DE CAPA (OPCIONAL)',
    imageSelected: '✓ Imagem Selecionada',
    chooseImage: '+ Escolher Imagem da Galeria',
    removeImage: 'Remover Imagem',
    saveChanges: 'SALVAR ALTERAÇÕES',
    createBand: 'CRIAR NOVA BANDA',
    
    // Song Modal
    newSong: 'NOVA MÚSICA',
    editSong: 'EDITAR MÚSICA',
    songNameLabel: 'NOME DA MÚSICA *',
    originalBandLabel: 'BANDA ORIGINAL *',
    tagsLabel: 'TAGS ( , )',
    durationLabel: 'DURAÇÃO (MM:SS)',
    lyricsLabel: 'Letra 📝',
    chordsLabel: 'Cifra 🎸',
    tabsLabel: 'Tab 🎼',
    defaultViewLabel: 'VISUALIZAÇÃO PADRÃO',
    scrollSpeedLabel: 'VELOCIDADE DO SCROLL',
    supportLinks: 'LINKS DE APOIO',
    addLink: '+ Adicionar Novo Link',
    removeLink: '✕ Remover Link',
    invalidDurationTitle: 'Duração Inválida',
    invalidDurationMsg: 'Por favor, insira a duração no formato MM:SS (ex: 03:45) ou deixe o campo vazio.',
    editSongContent: 'EDITAR CONTEÚDO DA MÚSICA',
    defaultScrollSpeed: 'VELOCIDADE DE ROLAGEM PADRÃO (AUTOSCROLL)',
    disabledLabel: 'Desativada ✕',
    saveSong: 'SALVAR MÚSICA',
    lyricsFormLabel: 'Letra',
    chordsFormLabel: 'Cifra',
    tabsFormLabel: 'Tablatura',
    
    // Setlist Modal
    newSetlist: 'NOVO SETLIST',
    editSetlist: 'EDITAR SETLIST',
    reorderBtn: 'REORDENAR',
    reorderTitle: 'REORDENAR REPERTÓRIO',
    reorderTip: 'Toque em uma música para selecioná-la, depois toque em outra posição para movê-la instantaneamente.',
    reorderTipDrag: 'Arraste as músicas segurando no ícone (☰) à direita para ordenar o repertório suavemente.',
    noteItem: 'ANOTAÇÃO / TEXTO',
    notePlaceholder: 'Digite sua anotação ou observação...',
    done: 'CONCLUÍDO',
    setlistNameLabel: 'NOME DO EVENTO / SHOW *',
    typeLabel: 'TIPO DE ROTEIRO',
    dateLabel: 'DATA DO EVENTO',
    localLabel: 'LOCAL / VENUE',
    cachêLabel: 'CACHÊ (R$)',
    notesLabel: 'OBSERVAÇÕES DO SHOW (GERAL)',
    songsLabel: 'MÚSICAS DISPONÍVEIS',
    repertoire: 'repertório',
    rehearsal: 'ensaio',
    show: 'show',
    dragTip: 'Dica: Toque e arraste os itens selecionados abaixo para ordenar.',
    noSongsInSetlist: 'Nenhuma música selecionada para este setlist ainda.',
    searchPlaceholder: 'Buscar...',
    presentationType: 'TIPO DE APRESENTAÇÃO',
    responsibleBand: 'BANDA RESPONSÁVEL',
    registerBandFirst: '⚠️ Cadastre uma banda primeiro!',
    createSetlist: 'CRIAR SETLIST',
    attention: 'Atenção',
    alertSetlistName: 'Informe o nome do setlist.',
    alertSelectBand: 'Selecione uma banda associada.',
    alertSetlistDate: 'Informe a data do setlist/ensaio/show.',
    alertSelectSong: 'Selecione pelo menos uma música para o setlist.',
    alertSongName: 'Informe o nome da música.',
    alertOriginalBand: 'Informe a banda original.',
    deleteBandConfirmTitle: 'Excluir Banda',
    deleteBandConfirmMsg: 'Tem certeza que deseja excluir a banda "{name}"? Setlists vinculados a esta banda terão o campo de banda limpo.',
    deleteSongConfirmTitle: 'Excluir Música',
    deleteSongConfirmMsg: 'Tem certeza de que deseja excluir esta música do banco de dados global?',
    deleteSongError: 'Não foi possível excluir a música.',
    deleteSetlistConfirmTitle: 'Excluir Setlist',
    deleteSetlistConfirmMsg: 'Tem certeza de que deseja excluir este setlist?',
    deleteSetlistError: 'Não foi possível excluir o setlist.',
    
    // Setlist Card
    estimatedTime: 'Tempo Estimado',
    venue: 'Local',
    songsTitle: 'MÚSICAS DO ROTEIRO',
    rehearsalNotesPlaceholder: 'Observações do ensaio (opcional)',
    noSongsInCard: 'Nenhum setlist encontrado para os filtros ativos. Clique em "+ Setlist" no topo para criar!',
    
    // Detail Modal
    detailTitle: 'DETALHES DO SETLIST',
    cacheText: 'Cachê',
    typeText: 'Tipo',
    songsCount: 'Músicas',
    noSongsInDetail: 'Nenhuma música associada a este setlist.',
    startStageBtn: '🎤 INICIAR MODO PERFORMANCE (PALCO)',
    
    // Performance Mode
    pause: 'PAUSA',
    rehearsalReport: '📋 ROTEIRO COMPLETO',
    pauseTitle: 'PAUSA / INTERVALO',
    noLyrics: 'Nenhuma letra cadastrada para esta música.',
    noChords: 'Nenhuma cifra cadastrada para esta música.',
    noTabs: 'Nenhuma tablatura cadastrada para esta música.',
    timerCountdown: 'Contagem Regressiva',
    timerPaused: 'Pausado',
    timerFinished: 'PAUSA FINALIZADA!',
    timerNoLimit: 'SEM LIMITE DE TEMPO',
    pauseTimer: '⏸ PAUSAR CONTADOR',
    startTimer: '▶ INICIAR CONTADOR',
    resetTimer: '🔄 RESETAR',
    closeList: 'FECHAR LISTA',
    
    myBandsCarouselSubtitle: '🎸 Minhas Bandas (Toque longo para editar/excluir)',
    addToSetlist: '+ ADICIONAR AO ROTEIRO',
    alertSelectSongOrPauseFirst: 'Selecione uma música ou pausa primeiro.',
    importTitleSetlist: 'IMPORTAR SETLIST',
    importTitleSong: 'IMPORTAR MÚSICA',
    importDescSetlist: 'Selecione o arquivo físico de setlist (.json) ou cole o código no editor abaixo para importar.',
    importDescSong: 'Selecione o arquivo físico de música (.json) ou cole o código no editor abaixo para importar.',
    fileTypeLabelSong: 'de música',
    fileTypeLabelSetlist: 'de setlist',

    noBand: 'Sem Banda',
    songsBadge: 'mús.',

    // Import Modal
    importTitle: 'IMPORTAR SETLIST / MÚSICA',
    pasteJsonLabel: 'COLE O CÓDIGO JSON AQUI',
    importBtn: '✕ IMPORTAR DADOS',
    importSuccessSong: 'Música importada com sucesso!',
    importSuccessSetlist: 'Setlist importado com sucesso!',
    importErrorTitle: 'Erro',
    importErrorMsg: 'Não foi possível importar os dados. Verifique a formatação do JSON.',
    invalidJsonMsg: 'O código colado não é um JSON válido.',
    success: 'Sucesso',
    fileLoadedAlert: 'Arquivo carregado! Clique em IMPORTAR AGORA para finalizar.',
    fileReadError: 'Não foi possível ler o arquivo selecionado.',
    selectFileLabel: 'SELECIONAR ARQUIVO JSON',
    orPasteCode: 'OU COLE O CÓDIGO TEXTO',
    importNow: 'IMPORTAR AGORA',
    
    // Share / Export Actions
    shareTitle: 'Compartilhar',
    exportDocSuccess: 'Documento exportado com sucesso!',

    // About Screen
    loadingDatabase: 'Carregando banco...',
    aboutHeader: 'ℹ️ SOBRE',
    aboutTheApp: 'O Aplicativo',
    aboutAppDesc: 'O Setlist Band Manager é uma ferramenta profissional projetada para auxiliar músicos, bandas e produtores a organizarem seu repertório e seus roteiros de shows de forma impecável.',
    aboutFeatures: 'Funcionalidades Principais',
    aboutDev: 'DESENVOLVIDO POR:',
    versionText: 'Versão',
    aboutFeature1Title: 'Gestão Multibandas',
    aboutFeature1Desc: 'Cadastre e gerencie o repertório de diferentes projetos musicais.',
    aboutFeature2Title: 'Repertório Sanfona',
    aboutFeature2Desc: 'Guarde cifras, tonalidades, duração e links de apoio de forma organizada.',
    aboutFeature3Title: 'Modo Palco',
    aboutFeature3Desc: 'Visualize cifras e letras com rolagem automática e letreiro dinâmico no palco.',
    aboutFeature4Title: 'Ensaios Inteligentes',
    aboutFeature4Desc: 'Avalie o desempenho das músicas no ensaio com cores (verde/amarelo/vermelho), crie observações para cada música e salve tudo no histórico.',
    aboutFeature5Title: 'Compartilhamento e Exportação',
    aboutFeature5Desc: 'Importe e exporte setlists em JSON e gere arquivos Word profissionais formatados em A4.',
    aboutFeature6Title: 'Multilíngue e Personalização',
    aboutFeature6Desc: 'Alterne o idioma entre Português, Inglês e Espanhol e escolha cores primárias e secundárias premium.',
    aboutFeature7Title: 'Fixados e Favoritos',
    aboutFeature7Desc: 'Marque setlists e músicas com estrela para mantê-los fixados no topo automaticamente.',
    aboutFeature8Title: 'Múltiplas Tags e Filtros',
    aboutFeature8Desc: 'Cadastre músicas com múltiplas tags por vírgula e filtre combinando até 3 tags simultâneas.',
    aboutFeature9Title: 'Reordenação por Toque e Arraste',
    aboutFeature9Desc: 'Organize a ordem das músicas no setlist arrastando de forma suave e rápida com física de mola e vibração.',
    aboutFeature10Title: 'Linhas de Anotação e Notas',
    aboutFeature10Desc: 'Adicione avisos, tons, observações ou quebras de seção diretamente no setlist como slides especiais de tela inteira no Modo Palco.',
    backupTipsTitle: '⚠️ Dicas de Backup e Segurança',
    protectDataLabel: 'Como proteger seus dados de repertório:',
    tip1: '• Não desinstale para atualizar: Para instalar novas atualizações, basta abrir o APK atualizado e instalá-lo por cima do antigo. Caso você desinstale o app completamente, o banco de dados local será deletado do celular pelo sistema operacional.',
    tip2: '• Faça backups manuais: Salve seus setlists mais importantes gerando os códigos de exportação com o botão de compartilhamento e guardando-os no WhatsApp ou bloco de notas.',
    tip3: '• Restaurar dados: Se precisar reinstalar o aplicativo ou trocar de aparelho, utilize a opção Importar na aba correspondente e cole o código ou selecione o arquivo para recuperar tudo instantaneamente.',
    backupAllBtn: 'GERAR BACKUP TOTAL',
    restoreBackupBtn: 'RESTAURAR BACKUP',
    restoreBackupTitle: 'RESTAURAR BACKUP',
    restoreBackupDesc: 'Selecione o arquivo de backup (.json) ou cole o código no editor abaixo para restaurar todos os dados.',
    fileTypeLabelBackup: 'de backup',
    backupCreatedAlert: 'Backup criado com sucesso!',
    codeCopied: 'e copiado para a área de transferência!',
    backupAllTitle: 'Backup Total de Dados',
    songAlreadyExists: 'A música "{name}" já existe no banco de dados e não foi duplicada.',
  },
  en: {
    // Tabs
    home: 'Home',
    songs: 'Songs',
    setlists: 'Setlists',
    about: 'About',
    
    // Home Tab
    myBands: 'My Bands',
    quickStats: 'QUICK STATISTICS',
    totalSongs: 'Total Songs',
    totalSetlists: 'Total Setlists',
    noBands: 'No bands registered yet. Click "+ Band" at the top to create one!',
    noSongs: 'No songs found. Click "+ Song" at the top to register one!',
    upcomingEvents: 'UPCOMING EVENTS',
    
    // Song / Band / Setlist Actions
    edit: 'Edit',
    delete: 'Delete',
    copy: 'Duplicate',
    share: 'Share',
    exportWord: 'Export Word',
    startStage: 'Stage',
    addBand: '+ BAND',
    addSong: '+ SONG',
    addSetlist: '+ SETLIST',
    importBtnText: '📥 IMPORT',
    searchPlaceholderDesc: 'Search by title, artist, or style...',
    
    // Settings / Theme Modal
    themeAppearance: 'THEME & APPEARANCE',
    themeMode: 'THEME MODE',
    dark: 'Dark 🌙',
    light: 'Light ☀️',
    primaryColor: 'PRIMARY COLOR',
    secondaryColor: 'SECONDARY COLOR',
    appLanguage: 'APP LANGUAGE',
    save: 'SAVE SETTINGS',
    cancel: 'Cancel',
    optionsBtn: 'Options',
    optionsTitle: 'Options',
    closeBtn: 'CLOSE',
    
    // Band Modal
    newBand: 'NEW BAND',
    editBand: 'EDIT BAND',
    bandNameLabel: 'BAND NAME *',
    coverImageLabel: 'COVER IMAGE (OPTIONAL)',
    imageSelected: '✓ Image Selected',
    chooseImage: '+ Choose Image from Gallery',
    removeImage: 'Remove Image',
    saveChanges: 'SAVE CHANGES',
    createBand: 'CREATE NEW BAND',
    
    // Song Modal
    newSong: 'NEW SONG',
    editSong: 'EDIT SONG',
    songNameLabel: 'SONG NAME *',
    originalBandLabel: 'ORIGINAL BAND *',
    tagsLabel: 'TAGS ( , )',
    durationLabel: 'DURATION (MM:SS)',
    lyricsLabel: 'Lyrics 📝',
    chordsLabel: 'Chords 🎸',
    tabsLabel: 'Tab 🎼',
    defaultViewLabel: 'DEFAULT VIEW',
    scrollSpeedLabel: 'SCROLL SPEED',
    supportLinks: 'SUPPORT LINKS',
    addLink: '+ Add New Link',
    removeLink: '✕ Remove Link',
    invalidDurationTitle: 'Invalid Duration',
    invalidDurationMsg: 'Please enter the duration in MM:SS format (e.g. 03:45) or leave the field blank.',
    editSongContent: 'EDIT SONG CONTENT',
    defaultScrollSpeed: 'DEFAULT SCROLL SPEED (AUTOSCROLL)',
    disabledLabel: 'Disabled ✕',
    saveSong: 'SAVE SONG',
    lyricsFormLabel: 'Lyrics',
    chordsFormLabel: 'Chords',
    tabsFormLabel: 'Tabs',
    
    // Setlist Modal
    newSetlist: 'NEW SETLIST',
    editSetlist: 'EDIT SETLIST',
    reorderBtn: 'REORDER',
    reorderTitle: 'REORDER SETLIST',
    reorderTip: 'Tap on a song to select it, then tap another position to move it instantly.',
    reorderTipDrag: 'Drag songs by holding the handle (☰) on the right to reorder the setlist smoothly.',
    noteItem: 'NOTE / TEXT',
    notePlaceholder: 'Type your note or observation...',
    done: 'DONE',
    setlistNameLabel: 'EVENT / SHOW NAME *',
    typeLabel: 'SETLIST TYPE',
    dateLabel: 'EVENT DATE',
    localLabel: 'LOCAL / VENUE',
    cachêLabel: 'CACHET ($)',
    notesLabel: 'SHOW NOTES (GENERAL)',
    songsLabel: 'AVAILABLE SONGS',
    repertoire: 'repertoire',
    rehearsal: 'rehearsal',
    show: 'show',
    dragTip: 'Tip: Tap and drag selected items below to order.',
    noSongsInSetlist: 'No songs selected for this setlist yet.',
    searchPlaceholder: 'Search...',
    presentationType: 'PRESENTATION TYPE',
    responsibleBand: 'RESPONSIBLE BAND',
    registerBandFirst: '⚠️ Register a band first!',
    createSetlist: 'CREATE SETLIST',
    attention: 'Attention',
    alertSetlistName: 'Please enter the setlist name.',
    alertSelectBand: 'Please select an associated band.',
    alertSetlistDate: 'Please enter the setlist date.',
    alertSelectSong: 'Please select at least one song for the setlist.',
    alertSongName: 'Please enter the song name.',
    alertOriginalBand: 'Please enter the original band.',
    deleteBandConfirmTitle: 'Delete Band',
    deleteBandConfirmMsg: 'Are you sure you want to delete the band "{name}"? Linked setlists will have their band field cleared.',
    deleteSongConfirmTitle: 'Delete Song',
    deleteSongConfirmMsg: 'Are you sure you want to delete this song from the global database?',
    deleteSongError: 'Could not delete the song.',
    deleteSetlistConfirmTitle: 'Delete Setlist',
    deleteSetlistConfirmMsg: 'Are you sure you want to delete this setlist?',
    deleteSetlistError: 'Could not delete the setlist.',
    
    // Setlist Card
    estimatedTime: 'Estimated Time',
    venue: 'Venue',
    songsTitle: 'SETLIST SONGS',
    rehearsalNotesPlaceholder: 'Rehearsal notes (optional)',
    noSongsInCard: 'No setlist found for active filters. Click "+ Setlist" at the top to create one!',
    
    // Detail Modal
    detailTitle: 'SETLIST DETAILS',
    cacheText: 'Cachet',
    typeText: 'Type',
    songsCount: 'Songs',
    noSongsInDetail: 'No songs associated with this setlist.',
    startStageBtn: '🎤 START PERFORMANCE MODE (STAGE)',
    
    // Performance Mode
    pause: 'PAUSE',
    rehearsalReport: '📋 FULL SETLIST',
    pauseTitle: 'PAUSE / BREAK',
    noLyrics: 'No lyrics registered for this song.',
    noChords: 'No chords registered for this song.',
    noTabs: 'No tabs registered for this song.',
    timerCountdown: 'Countdown',
    timerPaused: 'Paused',
    timerFinished: 'PAUSE FINISHED!',
    timerNoLimit: 'NO TIME LIMIT',
    pauseTimer: '⏸ PAUSE TIMER',
    startTimer: '▶ START TIMER',
    resetTimer: '🔄 RESET',
    closeList: 'CLOSE LIST',
    
    myBandsCarouselSubtitle: '🎸 My Bands (Long press to edit/delete)',
    addToSetlist: '+ ADD TO SETLIST',
    alertSelectSongOrPauseFirst: 'Select a song or pause first.',
    importTitleSetlist: 'IMPORT SETLIST',
    importTitleSong: 'IMPORT SONG',
    importDescSetlist: 'Select the setlist file (.json) or paste the code in the editor below to import.',
    importDescSong: 'Select the song file (.json) or paste the code in the editor below to import.',
    fileTypeLabelSong: 'song',
    fileTypeLabelSetlist: 'setlist',

    noBand: 'No Band',
    songsBadge: 'songs',

    // Import Modal
    importTitle: 'IMPORT SETLIST / SONG',
    pasteJsonLabel: 'PASTE JSON CODE HERE',
    importBtn: '✕ IMPORT DATA',
    importSuccessSong: 'Song imported successfully!',
    importSuccessSetlist: 'Setlist imported successfully!',
    importErrorTitle: 'Error',
    importErrorMsg: 'Could not import data. Please check JSON formatting.',
    invalidJsonMsg: 'Pasted code is not a valid JSON.',
    success: 'Success',
    fileLoadedAlert: 'File loaded! Click IMPORT NOW to finish.',
    fileReadError: 'Could not read the selected file.',
    selectFileLabel: 'SELECT JSON FILE',
    orPasteCode: 'OR PASTE TEXT CODE',
    importNow: 'IMPORT NOW',
    
    // Share / Export Actions
    shareTitle: 'Share',
    exportDocSuccess: 'Document exported successfully!',

    // About Screen
    loadingDatabase: 'Loading database...',
    aboutHeader: 'ℹ️ ABOUT',
    aboutTheApp: 'The App',
    aboutAppDesc: 'Setlist Band Manager is a professional tool designed to help musicians, bands, and producers organize their repertoire and setlists flawlessly.',
    aboutFeatures: 'Key Features',
    aboutDev: 'DEVELOPER:',
    versionText: 'Version',
    aboutFeature1Title: 'Multi-band Management',
    aboutFeature1Desc: 'Register and manage the repertoire of different musical projects.',
    aboutFeature2Title: 'Repertoire Book',
    aboutFeature2Desc: 'Keep chords, keys, duration, and support links organized.',
    aboutFeature3Title: 'Stage Mode',
    aboutFeature3Desc: 'View chords and lyrics with auto-scroll and dynamic marquee on stage.',
    aboutFeature4Title: 'Smart Rehearsals',
    aboutFeature4Desc: 'Rate song performance in rehearsals with colors (green/yellow/red), create specific notes for each song, and save history.',
    aboutFeature5Title: 'Sharing & Exporting',
    aboutFeature5Desc: 'Import and export setlists in JSON and generate professional A4 Word files.',
    aboutFeature6Title: 'Multilingual & Themes',
    aboutFeature6Desc: 'Switch language between Portuguese, English, and Spanish and customize appearance with premium theme colors.',
    aboutFeature7Title: 'Pinned & Favorites',
    aboutFeature7Desc: 'Mark setlists and songs with a star to keep them automatically pinned at the top.',
    aboutFeature8Title: 'Multiple Tags & Filters',
    aboutFeature8Desc: 'Register songs with multiple tags separated by comma and filter combining up to 3 tags simultaneously.',
    aboutFeature9Title: 'Drag-and-Drop Reordering',
    aboutFeature9Desc: 'Reorganize setlist song order by dragging smoothly and quickly with physics and haptic feedback.',
    aboutFeature10Title: 'Setlist Notes & Observations',
    aboutFeature10Desc: 'Add notes, warnings, keys, or section breaks inside the setlist, showing as full-screen slides in Stage Mode.',
    backupTipsTitle: '⚠️ Backup & Security Tips',
    protectDataLabel: 'How to protect your repertoire data:',
    tip1: '• Do not uninstall to update: To install new updates, simply open the updated APK and install it over the old one. If you uninstall the app completely, the local database will be deleted from the phone by the OS.',
    tip2: '• Make manual backups: Save your most important setlists by generating export codes or JSON files with the share button and keeping them in WhatsApp or notes.',
    tip3: '• Restore data: If you need to reinstall the app or change devices, use the Import option in the corresponding tab and paste the code or select the file to recover everything instantly.',
    backupAllBtn: 'GENERATE TOTAL BACKUP',
    restoreBackupBtn: 'RESTORE BACKUP',
    restoreBackupTitle: 'RESTORE BACKUP',
    restoreBackupDesc: 'Select the backup file (.json) or paste the code in the editor below to restore all data.',
    fileTypeLabelBackup: 'backup',
    backupCreatedAlert: 'Backup created successfully!',
    codeCopied: 'and copied to clipboard!',
    backupAllTitle: 'Total Data Backup',
    songAlreadyExists: 'The song "{name}" already exists in the database and was not duplicated.',
  },
  es: {
    // Tabs
    home: 'Inicio',
    songs: 'Canciones',
    setlists: 'Setlists',
    about: 'Acerca',
    
    // Home Tab
    myBands: 'Mis Bandas',
    quickStats: 'ESTATÍSTICAS RÁPIDAS',
    totalSongs: 'Total de Canciones',
    totalSetlists: 'Total de Setlists',
    noBands: 'Ninguna banda registrada aún. ¡Haz clic en "+ Banda" arriba para crear una!',
    noSongs: 'Ninguna canción encontrada. ¡Haz clic en "+ Canción" arriba para registrar una!',
    upcomingEvents: 'PRÓXIMOS EVENTOS',
    
    // Song / Band / Setlist Actions
    edit: 'Editar',
    delete: 'Eliminar',
    copy: 'Duplicar',
    share: 'Compartir',
    exportWord: 'Exportar Word',
    startStage: 'Escenario',
    addBand: '+ BANDA',
    addSong: '+ CANCIÓN',
    addSetlist: '+ SETLIST',
    importBtnText: '📥 IMPORTAR',
    searchPlaceholderDesc: 'Buscar por título, artista o estilo...',
    
    // Settings / Theme Modal
    themeAppearance: 'TEMA Y APARIENCIA',
    themeMode: 'MODO DE TEMA',
    dark: 'Oscuro 🌙',
    light: 'Claro ☀️',
    primaryColor: 'COLOR PRIMARIO',
    secondaryColor: 'COLOR SECUNDARIO',
    appLanguage: 'IDIOMA DE LA APP',
    save: 'GUARDAR AJUSTES',
    cancel: 'Cancelar',
    optionsBtn: 'Opciones',
    optionsTitle: 'Opciones',
    closeBtn: 'CERRAR',
    
    // Band Modal
    newBand: 'NUEVA BANDA',
    editBand: 'EDITAR BANDA',
    bandNameLabel: 'NOMBRE DE LA BANDA *',
    coverImageLabel: 'FOTO DE PORTADA (OPCIONAL)',
    imageSelected: '✓ Imagen Seleccionada',
    chooseImage: '+ Elegir Imagen de la Galería',
    removeImage: 'Eliminar Imagen',
    saveChanges: 'GUARDAR CAMBIOS',
    createBand: 'CREAR NUEVA BANDA',
    
    // Song Modal
    newSong: 'NUEVA CANCIÓN',
    editSong: 'EDITAR CANCIÓN',
    songNameLabel: 'NOMBRE DE LA CANCIÓN *',
    originalBandLabel: 'BANDA ORIGINAL *',
    tagsLabel: 'ETIQUETAS ( , )',
    durationLabel: 'DURACIÓN (MM:SS)',
    lyricsLabel: 'Letra 📝',
    chordsLabel: 'Acordes 🎸',
    tabsLabel: 'Tab 🎼',
    defaultViewLabel: 'VISTA PREDETERMINADA',
    scrollSpeedLabel: 'VELOCIDADE DE SCROLL',
    supportLinks: 'ENLACES DE APOYO',
    addLink: '+ Añadir Nuevo Enlace',
    removeLink: '✕ Eliminar Enlace',
    invalidDurationTitle: 'Duración Inválida',
    invalidDurationMsg: 'Por favor, ingrese la duración en formato MM:SS (ej: 03:45) o deje el campo vacío.',
    editSongContent: 'EDITAR CONTENIDO DE LA CANCIÓN',
    defaultScrollSpeed: 'VELOCIDAD DE DESPLAZAMIENTO PREDETERMINADA',
    disabledLabel: 'Desactivado ✕',
    saveSong: 'GUARDAR CANCIÓN',
    lyricsFormLabel: 'Letra',
    chordsFormLabel: 'Acordes',
    tabsFormLabel: 'Tablatura',
    
    // Setlist Modal
    newSetlist: 'NUEVO SETLIST',
    editSetlist: 'EDITAR SETLIST',
    reorderBtn: 'REORDENAR',
    reorderTitle: 'REORDENAR SETLIST',
    reorderTip: 'Toca una canción para seleccionarla, luego toca otra posición para moverla instantáneamente.',
    reorderTipDrag: 'Arrastre las canciones sosteniendo el ícono (☰) a la derecha para ordenar el setlist suavemente.',
    noteItem: 'NOTA / TEXTO',
    notePlaceholder: 'Escribe tu nota u observación...',
    done: 'CONCLUIDO',
    setlistNameLabel: 'NOMBRE DEL EVENTO / SHOW *',
    typeLabel: 'TIPO DE ROTEIRO',
    dateLabel: 'FECHA DEL EVENTO',
    localLabel: 'LUGAR / VENUE',
    cachêLabel: 'PAGO ($)',
    notesLabel: 'NOTAS DEL SHOW (GENERAL)',
    songsLabel: 'CANCIONES DISPONIBLES',
    repertoire: 'repertorio',
    rehearsal: 'ensayo',
    show: 'show',
    dragTip: 'Dica: Toca y arrastra los elementos seleccionados abajo para ordenar.',
    noSongsInSetlist: 'Ninguna canción seleccionada para este setlist aún.',
    searchPlaceholder: 'Buscar...',
    presentationType: 'TIPO DE PRESENTACIÓN',
    responsibleBand: 'BANDA RESPONSABLE',
    registerBandFirst: '⚠️ ¡Registre una banda primero!',
    createSetlist: 'CREAR SETLIST',
    attention: 'Atención',
    alertSetlistName: 'Por favor, introduzca el nombre del setlist.',
    alertSelectBand: 'Por favor, seleccione una banda asociada.',
    alertSetlistDate: 'Por favor, introduzca la fecha del setlist.',
    alertSelectSong: 'Por favor, seleccione al menos una canción para el setlist.',
    alertSongName: 'Por favor, introduzca el nombre de la canción.',
    alertOriginalBand: 'Por favor, introduzca la banda original.',
    deleteBandConfirmTitle: 'Eliminar Banda',
    deleteBandConfirmMsg: '¿Está seguro de que desea eliminar la banda "{name}"? Los setlists vinculados tendrán su campo de banda borrado.',
    deleteSongConfirmTitle: 'Eliminar Canción',
    deleteSongConfirmMsg: '¿Está seguro de que desea eliminar esta canción de la base de datos global?',
    deleteSongError: 'No se pudo eliminar la canción.',
    deleteSetlistConfirmTitle: 'Eliminar Setlist',
    deleteSetlistConfirmMsg: '¿Está seguro de que desea eliminar este setlist?',
    deleteSetlistError: 'No se pudo eliminar el setlist.',
    
    // Setlist Card
    estimatedTime: 'Tiempo Estimado',
    venue: 'Lugar',
    songsTitle: 'CANCIONES DEL SETLIST',
    rehearsalNotesPlaceholder: 'Notas del ensayo (opcional)',
    noSongsInCard: 'Ningún setlist encontrado para los filtros activos. ¡Haz clic en "+ Setlist" arriba para crear uno!',
    
    // Detail Modal
    detailTitle: 'DETALLES DEL SETLIST',
    cacheText: 'Pago',
    typeText: 'Tipo',
    songsCount: 'Canciones',
    noSongsInDetail: 'Ninguna canción asociada a este setlist.',
    startStageBtn: '🎤 INICIAR MODO PERFORMANCE (ESCENARIO)',
    
    // Performance Mode
    pause: 'PAUSA',
    rehearsalReport: '📋 SETLIST COMPLETO',
    pauseTitle: 'PAUSA / INTERVALO',
    noLyrics: 'Ninguna letra registrada para esta canción.',
    noChords: 'Ningún acorde registrado para esta canción.',
    noTabs: 'Ninguna tablatura registrada para esta canción.',
    timerCountdown: 'Cuenta Regresiva',
    timerPaused: 'Pausado',
    timerFinished: '¡PAUSA FINALIZADA!',
    timerNoLimit: 'SIN LÍMITE DE TEMPO',
    pauseTimer: '⏸ PAUSAR TEMPORIZADOR',
    startTimer: '▶ INICIAR TEMPORIZADOR',
    resetTimer: '🔄 REINICIAR',
    closeList: 'CERRAR LISTA',
    
    myBandsCarouselSubtitle: '🎸 Mis Bandas (Mantén presionado para editar/eliminar)',
    addToSetlist: '+ AÑADIR AL SETLIST',
    alertSelectSongOrPauseFirst: 'Seleccione una canción o pausa primero.',
    importTitleSetlist: 'IMPORTAR SETLIST',
    importTitleSong: 'IMPORTAR CANCIÓN',
    importDescSetlist: 'Seleccione el archivo del setlist (.json) o pegue el código en el editor abajo para importar.',
    importDescSong: 'Seleccione el archivo de la canción (.json) o pegue el código en el editor abajo para importar.',
    fileTypeLabelSong: 'canción',
    fileTypeLabelSetlist: 'setlist',

    noBand: 'Sin Banda',
    songsBadge: 'canc.',

    // Import Modal
    importTitle: 'IMPORTAR SETLIST / CANCIÓN',
    pasteJsonLabel: 'PEGAR CÓDIGO JSON AQUÍ',
    importBtn: '✕ IMPORTAR DADOS',
    importSuccessSong: '¡Canción importada con éxito!',
    importSuccessSetlist: '¡Setlist importado con éxito!',
    importErrorTitle: 'Error',
    importErrorMsg: 'No se pudieron importar los datos. Verifique el formato JSON.',
    invalidJsonMsg: 'El código pegado no es un JSON válido.',
    success: 'Éxito',
    fileLoadedAlert: '¡Archivo cargado! Haga clic en IMPORTAR AHORA para finalizar.',
    fileReadError: 'No se pudo leer el archivo seleccionado.',
    selectFileLabel: 'SELECCIONAR ARCHIVO JSON',
    orPasteCode: 'O PEGUE EL CÓDIGO DE TEXTO',
    importNow: 'IMPORTAR AHORA',
    
    // Share / Export Actions
    shareTitle: 'Compartir',
    exportDocSuccess: '¡Documento exportado con éxito!',

    // About Screen
    loadingDatabase: 'Cargando base de datos...',
    aboutHeader: 'ℹ️ ACERCA DE',
    aboutTheApp: 'La Aplicación',
    aboutAppDesc: 'Setlist Band Manager es una herramienta profesional diseñada para ayudar a músicos, bandas y productores a organizar su repertorio y setlists de manera impecable.',
    aboutFeatures: 'Funcionalidades Clave',
    aboutDev: 'DESARROLLADO POR:',
    versionText: 'Versión',
    aboutFeature1Title: 'Gestão Multibandas',
    aboutFeature1Desc: 'Registre y gestione el repertorio de diferentes proyectos musicales.',
    aboutFeature2Title: 'Directorio de Repertorio',
    aboutFeature2Desc: 'Guarde acordes, tonos, duración y enlaces de apoyo organizados.',
    aboutFeature3Title: 'Modo Escenario',
    aboutFeature3Desc: 'Vea acordes y letras con desplazamiento automático y marquesina dinámica.',
    aboutFeature4Title: 'Ensayos Inteligentes',
    aboutFeature4Desc: 'Evalúe el rendimiento de las canciones en el ensayo con colores (verde/amarillo/rojo), cree observaciones específicas por canción y guarde el historial.',
    aboutFeature5Title: 'Compartir y Exportar',
    aboutFeature5Desc: 'Importe y exporte setlists en JSON y genere archivos Word A4 profesionales.',
    aboutFeature6Title: 'Soporte Multilingüe y Temas',
    aboutFeature6Desc: 'Cambie entre Portugués, Inglés y Español y personalice el diseño con colores de tema del tema premium.',
    aboutFeature7Title: 'Fijados y Favoritos',
    aboutFeature7Desc: 'Marque setlists y canciones con una estrella para mantenerlos fijados al principio automáticamente.',
    aboutFeature8Title: 'Múltiples Etiquetas & Filtros',
    aboutFeature8Desc: 'Registre canciones con múltiples etiquetas por coma y filtre combinando hasta 3 etiquetas simultáneas.',
    aboutFeature9Title: 'Reordenación por Arrastre',
    aboutFeature9Desc: 'Organice el orden de las canciones en el setlist arrastrando de forma suave y rápida con física de muelle y vibración.',
    aboutFeature10Title: 'Líneas de Anotación y Notas',
    aboutFeature10Desc: 'Agregue avisos, tonos, observaciones o saltos de sección en el setlist como diapositivas de pantalla completa en el Modo Escenario.',
    backupTipsTitle: '⚠️ Consejos de Copia de Seguridad y Seguridad',
    protectDataLabel: 'Cómo proteger los datos de su repertorio:',
    tip1: '• No desinstale para actualizar: Para instalar nuevas actualizaciones, simplemente abra el APK actualizado e instálelo sobre el antiguo. Si desinstala la aplicación por completo, el sistema operativo borrará la base de datos local del teléfono.',
    tip2: '• Realice copias de seguridad manuales: Guarde sus setlists más importantes generando códigos de exportación o archivos JSON con el botón compartir y guardándolos en WhatsApp o notas.',
    tip3: '• Restaurar dados: Si necesita reinstalar la aplicación o cambiar de dispositivo, use la opción Importar en la pestaña correspondiente y pegue el código o seleccione el archivo para recuperar todo al instante.',
    backupAllBtn: 'GENERAR RESPALDO TOTAL',
    restoreBackupBtn: 'RESTAURAR RESPALDO',
    restoreBackupTitle: 'RESTAURAR RESPALDO',
    restoreBackupDesc: 'Seleccione el archivo de respaldo (.json) o pegue el código en el editor abajo para restaurar todos los datos.',
    fileTypeLabelBackup: 'respaldo',
    backupCreatedAlert: '¡Respaldo creado con éxito!',
    codeCopied: '¡y copiado al portapapeles!',
    backupAllTitle: 'Respaldo Total de Datos',
    songAlreadyExists: 'La canción "{name}" ya existe en la base de datos y no fue duplicada.',
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState('pt');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function loadLang() {
      try {
        const savedLang = await settingsService.getSetting('appLanguage', 'pt');
        setLanguageState(savedLang);
      } catch (error) {
        console.error('Error loading language setting:', error);
      } finally {
        setLoading(false);
      }
    }
    loadLang();
  }, []);

  const setLanguage = async (lang) => {
    setLanguageState(lang);
    await settingsService.setSetting('appLanguage', lang);
  };

  const t = (key) => {
    const langDict = translations[language] || translations.pt;
    return langDict[key] || translations.pt[key] || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
        loading
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
