import React, { createContext, useContext, useState, useEffect } from 'react';
import { settingsService } from '../services/settingsService';

const translations = {
  pt: {
    // Navegação e Abas
    home: 'Home',
    songs: 'Músicas',
    setlists: 'Setlists',
    options: 'Opções',
    about: 'Sobre',

    // Ações Gerais e Modais
    confirm: 'Confirmar',
    cancel: 'Cancelar',
    save: 'SALVAR',
    close: 'Fechar',
    closeBtn: 'FECHAR',
    edit: 'Editar',
    delete: 'Excluir',
    copy: 'Duplicar',
    share: 'Compartilhar',
    exportWord: 'Exportar Word',
    exportPdf: 'PDF',
    generatingPdf: 'Gerando PDF...',
    pdfSuccess: 'PDF criado com sucesso!',
    pdfError: 'Não foi possível gerar o PDF.',
    exportDocSuccess: 'Documento exportado com sucesso!',
    shareTitle: 'Compartilhar',
    sharePrompt: 'Escolha o formato:',
    shareAsFile: 'Arquivo Físico (.json)',
    shareAsFileDesc: 'Ideal para enviar para outros usuários do app importarem.',
    shareAsText: 'Texto Formatado',
    shareAsTextDesc: 'Ideal para enviar via WhatsApp, Telegram, etc.',
    shareSuccess: 'Compartilhado com sucesso!',
    shareOptionJson: 'Arquivo (.json)',
    shareOptionQr: 'Gerar QR Code',
    shareOptionText: 'Texto Formatado',
    shareOptionsTitle: 'Compartilhar',
    shareOptionsSubtitle: 'Escolha como deseja compartilhar:',
    shareQrTitle: 'Compartilhar via QR Code',
    shareQrDesc: 'Transfira para outro celular instantaneamente pela câmera ou PIN.',
    shareJsonTitle: 'Arquivo Físico (.json)',
    shareJsonDesc: 'Gere o arquivo para enviar no WhatsApp ou salvar de backup.',
    shareTextTitle: 'Texto Formatado',
    shareTextDesc: 'Envie os dados organizados em formato de texto para ler.',
    shareSongLabel: 'Música',
    shareSetlistLabel: 'Setlist',
    shareQrModalTitleSong: 'Compartilhar Música via QR',
    shareQrModalTitleSetlist: 'Compartilhar Setlist via QR',
    shareQrInstruction: 'Aponte a câmera do outro celular em Sincronizar ➔ Ler QR (ou digite o PIN) para importar este item instantaneamente!',
    shareQrPinLabel: 'CÓDIGO PIN',
    generatingItemQr: 'Gerando QR Code de compartilhamento...',
    itemTransferSuccessTitle: 'Transferência Concluída! 🎉',
    itemTransferSuccessMsg: 'O item foi transferido e importado com sucesso no outro dispositivo!',
    songImportedSuccess: 'Música "{name}" importada com sucesso!',
    setlistImportedSuccess: 'Setlist "{name}" importado com sucesso!',
    importOptionsTitle: 'Importar',
    importOptionsSubtitle: 'Escolha como deseja importar:',
    importSongSubtitle: 'Adicione uma nova música ao seu repertório',
    importSetlistSubtitle: 'Importe um roteiro de show ou ensaio',
    restoreBackupSubtitle: 'Restaure dados completos do aplicativo',
    importOptionQrTitle: 'Ler QR Code (Câmera ou PIN)',
    importOptionQrDesc: 'Aponte a câmera para o QR de outro celular/PC ou digite o PIN.',
    importOptionFileTitle: 'Selecionar Arquivo (.json)',
    importOptionFileDesc: 'Abra um arquivo .json salvo no seu aparelho ou WhatsApp.',
    importOptionTextTitle: 'Colar Código / Texto JSON',
    importOptionTextDesc: 'Cole o código ou texto copiado no editor de texto.',
    search: 'Buscar...',
    searchPlaceholder: 'Buscar...',
    searchPlaceholderDesc: 'Buscar por título, artista ou estilo...',
    emptyState: 'Nenhum registro encontrado.',
    attention: 'Atenção',
    success: 'Sucesso',
    info: 'Informação',
    optionsBtn: 'Opções',
    optionsTitle: 'Opções',
    done: 'CONCLUÍDO',

    // Tela Inicial (Home)
    myBands: 'Minhas Bandas',
    quickStats: 'ESTATÍSTICAS RÁPIDAS',
    totalSongs: 'Total de Músicas',
    totalSetlists: 'Total de Setlists',
    noBands: 'Nenhuma banda cadastrada ainda. Clique em "+ Banda" no topo para criar!',
    noSongs: 'Nenhuma música encontrada. Clique em "+ Música" no topo para cadastrar!',
    upcomingEvents: 'PRÓXIMOS EVENTOS',
    pastEvents: 'ANTIGAS',
    sortBy: 'ORDENAR POR:',
    band: 'Banda',
    song: 'Música',
    since: 'Desde',
    until: 'até',
    cachet: 'Cachê',
    accumulated: 'Acumulado',
    createBandBtn: '+ Criar Banda',
    createEventBtn: '+ Criar Evento',
    noBandsYet: 'Nenhuma banda cadastrada',
    noBandsSubtitle: 'Clique em "+ Banda" no topo para adicionar seu projeto musical.',
    searchRepertoire: 'Buscar no repertório...',
    noSongsInRepertoire: 'Nenhuma música no repertório',
    bandSongsSubtitle: 'As músicas vinculadas a esta banda aparecerão aqui.',
    addMember: 'Adicionar Integrante',
    activeMembers: 'INTEGRANTES ATIVOS',
    noMembersYet: 'Nenhum integrante cadastrado ainda',
    hideInactiveMembers: 'Ocultar Integrantes Inativos',
    showInactiveMembers: 'Exibir Integrantes Inativos',
    newEntry: 'Novo Lançamento',
    editEntry: 'Editar Lançamento',
    noShowsForBand: 'Nenhum show cadastrado para esta banda ainda.',
    untitledShow: 'Show Sem Nome',
    noLocationSpecified: 'Local não informado',
    showCachet: 'CACHÊ DE SHOW',
    toBeDefined: 'A DEFINIR',
    otherFinances: 'Outros',
    income: 'RECEITA',
    expense: 'DESPESA',
    newEvent: 'Novo Evento',
    noEventsScheduled: 'Nenhum evento agendado',
    bandEventsSubtitle: 'Os shows e ensaios desta banda aparecerão nesta lista.',
    linkCollectionSongs: 'Vincular Músicas da Coleção',
    searchCollectionSong: 'Buscar música da coleção...',
    descriptionLabel: 'Descrição: *',
    amountLabel: 'VALOR ($): *',
    entryTypeLabel: 'TIPO DE LANÇAMENTO:',
    today: 'Hoje',
    newMember: 'Novo Integrante',
    editMember: 'Editar Integrante',
    memberNameLabel: 'Nome: *',
    memberRoleLabel: 'Função / Instrumento (separe por vírgula):',
    memberPhoneLabel: 'Contato (WhatsApp):',
    startDateLabel: 'Data Início:',
    endDateLabel: 'Data Fim:',
    memberStatusLabel: 'Status do Integrante:',
    active: 'Ativo',
    inactive: 'Inativo',
    saveMember: 'Salvar Integrante',
    organizeRepertoire: 'Organizar Repertório',
    songNameAsc: 'Nome da Música (A - Z)',
    songNameDesc: 'Nome da Música (Z - A)',
    bandNameAsc: 'Banda Original (A - Z)',
    bandNameDesc: 'Banda Original (Z - A)',
    unsavedChangesMsg: 'Você tem alterações não salvas. Deseja salvar antes de sair?',
    discard: 'Descartar',
    leaveWithoutSaving: 'Sair sem Salvar',
    saveAndLeave: 'Salvar e Sair',
    tapToChange: 'Toque para alterar',
    untilCapital: 'Até',
    current: 'Atual',
    startDateFormLabel: 'DATA DE INÍCIO (DIA/MÊS/ANO)',
    endDateFormLabel: 'DATA FIM (OPCIONAL)',
    cacheSplitTitle: 'Divisão de Cachê por Integrante',
    totalCachet: 'Total Cachê:',
    divideEqually: 'Dividir Igualmente',
    noActiveMembersBand: 'Nenhum integrante ativo cadastrado nesta banda.',
    saveSplit: 'Salvar Divisão',
    noActiveMembers: 'Nenhum integrante ativo cadastrado.',
    repertoireStyles: 'Estilos do Repertório',
    noStyleTags: 'Nenhuma tag de estilo definida nas músicas desta banda.',
    financialSummary: 'Resumo Financeiro',
    incomes: 'Entradas',
    expenses: 'Saídas',
    balance: 'Saldo',
    myBandsCarouselSubtitle: 'Minhas Bandas (Toque longo para editar/excluir)',
    allBands: 'Todas as Bandas',
    showingAllBands: 'Exibindo todas as bandas',
    showingBandSetlist: 'Exibindo setlists de',
    showingBandSongs: 'Exibindo músicas de',
    viewAllBands: 'Ver todas as bandas',

    // Gestão de Bandas
    bands: 'Bandas / Projetos',
    addBand: '+ Banda',
    newBand: 'NOVA BANDA',
    editBand: 'EDITAR BANDA',
    bandNameLabel: 'NOME DA BANDA *',
    coverImageLabel: 'FOTO DE CAPA (OPCIONAL)',
    imageSelected: 'Imagem Selecionada',
    chooseImage: 'Escolher Imagem da Galeria',
    removeImage: 'Remover Imagem',
    saveChanges: 'SALVAR ALTERAÇÕES',
    createBand: 'CRIAR NOVA BANDA',
    deleteBandConfirmTitle: 'Excluir Banda',
    deleteBandConfirmMsg: 'Tem certeza que deseja excluir a banda "{name}"? Setlists vinculados a esta banda terão o campo de banda limpo.',
    deleteBandError: 'Não foi possível excluir a banda.',
    noBand: 'Sem Banda',

    // Gestão de Músicas
    addSong: '+ Música',
    newSong: 'NOVA MÚSICA',
    editSong: 'EDITAR MÚSICA',
    songNameLabel: 'NOME DA MÚSICA *',
    songNamePlaceholder: 'Nome',
    originalBandLabel: 'BANDA ORIGINAL *',
    originalBandPlaceholder: 'Banda',
    lyricsPlaceholder: 'Cole ou digite a letra da música aqui...',
    chordsPlaceholder: 'Cole ou digite a cifra com os acordes aqui (ex: [C] [G] [Am] [F])...',
    tabsPlaceholder: 'Cole ou digite a tablatura aqui (ex: e|---0---1---0---|)...',
    tagsPlaceholder: 'Ex: Rock, Pop, Anos 80',
    durationPlaceholder: 'Ex: 03:45',
    tagsLabel: 'TAGS ( , )',
    durationLabel: 'DURAÇÃO (MM:SS)',
    lyricsLabel: 'Letra',
    chordsLabel: 'Cifra',
    tabsLabel: 'Tablatura',
    lyricsFormLabel: 'Letra',
    chordsFormLabel: 'Cifra',
    tabsFormLabel: 'Tablatura',
    defaultViewLabel: 'VISUALIZAÇÃO PADRÃO',
    scrollSpeedLabel: 'VELOCIDADE DO SCROLL',
    defaultScrollSpeed: 'VELOCIDADE DE ROLAGEM PADRÃO (AUTOSCROLL)',
    supportLinks: 'LINKS DE APOIO',
    songDetails: 'DETALHES DA MÚSICA',
    cifras: 'Cifras',
    addLink: 'Adicionar Novo Link',
    removeLink: 'Remover Link',
    invalidDurationTitle: 'Duração Inválida',
    invalidDurationMsg: 'Por favor, insira a duração no formato MM:SS (ex: 03:45) ou deixe o campo vazio.',
    editSongContent: 'EDITAR CONTEÚDO DA MÚSICA',
    disabledLabel: 'Desativada',
    saveSong: 'SALVAR MÚSICA',
    alertSongName: 'Informe o nome da música.',
    alertOriginalBand: 'Informe a banda original.',
    deleteSongConfirmTitle: 'Excluir Música',
    deleteSongConfirmMsg: 'Tem certeza de que deseja excluir esta música do banco de dados global?',
    deleteSongError: 'Não foi possível excluir a música.',
    songAlreadyExists: 'A música "{name}" já existe no banco de dados e não foi duplicada.',
    songsBadge: 'mús.',
    tagAll: 'Todas as Tags',
    filterByTag: 'Filtrar por Tag',
    filterByStatus: 'Filtrar por Status',
    allStatuses: 'Todos',
    songInfoBpm: 'BPM',
    songInfoCapo: 'Capo',
    songInfoKey: 'Tom',

    songSingular: 'música',
    songPlural: 'músicas',

    // Gestão de Setlists
    addSetlist: '+ Setlist',
    newSetlist: 'NOVO SETLIST',
    editSetlist: 'EDITAR SETLIST',
    presentationType: 'TIPO DE EVENTO',
    show: 'Show',
    rehearsal: 'Ensaio',
    repertoire: 'Repertório',
    responsibleBand: 'BANDA RESPONSÁVEL *',
    registerBandFirst: 'Cadastre ao menos uma banda antes de criar o setlist.',
    setlistNameLabel: 'NOME DO SETLIST *',
    setlistNamePlaceholder: 'Nome do Evento',
    addSongBtn: '+ Música',
    addPauseBtn: '+ Pausa',
    addNoteBtn: '+ Anotação',
    datePlaceholder: 'AAAA-MM-DD',
    localPlaceholder: 'Ex: Bar do Zé, Estúdio X...',
    cachetPlaceholder: 'Ex: 500',
    dateLabel: 'DATA *',
    localLabel: 'LOCAL',
    cachêLabel: 'Cachê',
    notesLabel: 'OBSERVAÇÕES DO EVENTO',
    selectAll: 'Selecionar Todas',
    deselectAll: 'Desmarcar Todas',
    selectedSongsCount: 'selecionada(s)',
    noSongsCollection: 'Nenhuma música encontrada na coleção.',
    saveRepertoire: 'Salvar Repertório',
    linkCollectionSongs: 'MÚSICAS DA COLEÇÃO',
    searchCollectionSong: 'Buscar na coleção...',
    addSelectedCount: 'ADICIONAR SELECIONADAS',
    dragToReorderTip: 'Arraste por ☰ para reordenar',
    swipeToDeleteTip: 'Deslize para a esquerda para excluir',
    pauseItem: 'PAUSA',
    editPauseTitle: 'EDITAR PAUSA',
    editNoteTitle: 'EDITAR ANOTAÇÃO',
    typeNotePrompt: 'Digite sua anotação ou aviso...',
    durationExamplePlaceholder: 'Ex: 5 min, 10 min',
    foundPlural: 'encontrada(s)',
    copySetlistBtn: 'Copiar Setlist',
    setlistCopiedMsg: 'Setlist copiado com sucesso!',
    setlistCopyError: 'Não foi possível duplicar o setlist.',
    availableSongs: 'MÚSICAS DISPONÍVEIS',
    songsLabel: 'MÚSICAS DISPONÍVEIS',
    reorderBtn: 'REORDENAR',
    reorderTitle: 'REORDENAR ROTEIRO',
    reorderHelp: 'Arraste pelo ícone ☰ para reordenar. Toque no X para remover.',
    reorderTip: 'Toque em uma música para selecioná-la, depois toque em outra posição para movê-la instantaneamente.',
    reorderTipDrag: 'Arraste as músicas segurando no ícone (☰) à direita para ordenar o roteiro suavemente.',
    selectedSongsLabel: 'MÚSICAS SELECIONADAS (ARRASTE PARA ORDENAR)',
    createSetlist: 'CRIAR SETLIST',
    noteItem: 'ANOTAÇÃO',
    notePlaceholder: 'Digite observações do evento ou da apresentação...',
    alertSetlistName: 'Informe o nome do setlist.',
    alertSelectBand: 'Selecione uma banda associada.',
    alertSetlistDate: 'Informe a data do setlist.',
    alertSelectSong: 'Selecione pelo menos uma música para o setlist.',
    alertSelectSongOrPauseFirst: 'Selecione uma música ou pausa primeiro.',
    deleteSetlistConfirmTitle: 'Excluir Setlist',
    deleteSetlistConfirmMsg: 'Tem certeza de que deseja excluir este setlist?',
    deleteSetlistError: 'Não foi possível excluir o setlist.',
    addToSetlist: 'ADICIONAR AO ROTEIRO',
    noSongsInSetlist: 'Nenhuma música selecionada para este setlist ainda.',
    reorderDoneBtn: 'CONCLUÍDO',

    // Seletor Múltiplo de Músicas
    addSongsBtn: 'ADICIONAR MÚSICAS',
    selectSongsModalTitle: 'SELECIONAR MÚSICAS',
    selectAll: 'Marcar Todas',
    deselectAll: 'Desmarcar Todas',
    addSelectedCount: 'ADICIONAR SELECIONADAS',
    selectedCount: 'selecionada(s)',
    noSongsFoundInPicker: 'Nenhuma música encontrada.',

    // Card de Setlist e Detalhes
    dateText: 'Data',
    localText: 'Local',
    cachêText: 'Cachê',
    cacheText: 'Cachê',
    notesText: 'Observações',
    typeText: 'Tipo',
    songsCount: 'Músicas',
    songsTitle: 'MÚSICAS DO ROTEIRO',
    estimatedTime: 'Tempo Estimado',
    venue: 'Local',
    noSongsInCard: 'Nenhum setlist encontrado para os filtros ativos.',
    noSongsInDetail: 'Nenhuma música associada a este setlist.',
    detailTitle: 'DETALHES DO SETLIST',
    startStage: 'Palco',
    startStageBtn: 'MODO PALCO',
    setlistTabRepertoire: 'ROTEIRO',
    setlistTabDetails: 'DADOS DO EVENTO',
    editNoteTitle: 'EDITAR ANOTAÇÃO',
    editPauseTitle: 'EDITAR PAUSA',
    duplicateSetlist: 'Duplicar Setlist',
    createCopy: 'Criar Cópia',
    showsAndCaches: 'Shows e Cachês dos Eventos',
    noCachetDefined: 'Sem Cachê registrado',
    nextEventHero: 'PRÓXIMO EVENTO',
    membersBadge: 'integrantes',
    tapToEditSongTip: 'Toque na música para editar cifra/letra',
    dragToReorderTip: 'Arraste pelo ícone ☰ para reordenar',
    swipeToDeleteTip: 'Deslize para a esquerda para excluir',
    rehearsalNotesPlaceholder: 'Observações do ensaio (opcional)',

    // Modo Palco (Performance)
    pause: 'PAUSA',
    pauseTitle: 'PAUSA / INTERVALO',
    note: 'ANOTAÇÃO',
    noteTitle: 'ANOTAÇÃO / OBSERVAÇÃO',
    rehearsalReport: 'ROTEIRO COMPLETO',
    noLyrics: 'Nenhuma letra cadastrada para esta música.',
    noChords: 'Nenhuma cifra cadastrada para esta música.',
    noTabs: 'Nenhuma tablatura cadastrada para esta música.',
    noContentRegistered: 'Nenhum conteúdo cadastrado para esta música.',
    timerCountdown: 'Contagem Regressiva',
    timerPaused: 'Pausado',
    timerFinished: 'PAUSA FINALIZADA!',
    timerNoLimit: 'SEM LIMITE DE TEMPO',
    pauseTimer: 'PAUSAR CONTADOR',
    startTimer: 'INICIAR CONTADOR',
    resetTimer: 'RESETAR',
    closeList: 'FECHAR LISTA',

    // Modal de Importação
    importBtnText: 'Importar',
    importTitle: 'IMPORTAR DADOS',
    importTitleSetlist: 'IMPORTAR SETLIST',
    importTitleSong: 'IMPORTAR MÚSICA',
    importDescSetlist: 'Selecione o arquivo físico de setlist (.json) ou cole o código no editor abaixo para importar.',
    importDescSong: 'Selecione o arquivo físico de música (.json) ou cole o código no editor abaixo para importar.',
    fileTypeLabelSong: 'de música',
    fileTypeLabelSetlist: 'de setlist',
    fileTypeLabelBackup: 'de backup',
    pasteJsonLabel: 'COLE O CÓDIGO JSON AQUI',
    importBtn: 'IMPORTAR DADOS',
    importNow: 'IMPORTAR AGORA',
    selectFileLabel: 'SELECIONAR ARQUIVO JSON',
    orPasteCode: 'OU COLE O CÓDIGO TEXTO',
    importSuccessSong: 'Música importada com sucesso!',
    importSuccessSetlist: 'Setlist importado com sucesso!',
    importErrorTitle: 'Erro ao Importar',
    importErrorMsg: 'Não foi possível importar os dados. Verifique a formatação do JSON.',
    invalidJsonMsg: 'O código colado não é um JSON válido.',
    fileLoadedAlert: 'Arquivo carregado! Clique em IMPORTAR AGORA para finalizar.',
    fileReadError: 'Não foi possível ler o arquivo selecionado.',

    // Tema e Aparência
    themeAppearance: 'TEMA E APARÊNCIA',
    themeMode: 'MODO DO TEMA',
    dark: 'Escuro',
    light: 'Claro',
    primaryColor: 'COR PRIMÁRIA',
    secondaryColor: 'COR SECUNDÁRIA',
    appLanguage: 'IDIOMA DO APLICATIVO',

    // Backup e Restauração
    backupSectionTitle: 'BACKUP E RESTAURAÇÃO',
    backupSubtitle: 'Exporte ou importe todo o banco de dados do app (bandas, músicas e setlists) com total segurança.',
    backupExportBtn: 'BACKUP TOTAL (EXPORTAR)',
    backupImportBtn: 'RESTAURAR BACKUP (IMPORTAR)',
    backupExportSuccess: 'Backup exportado com sucesso! Arquivo pronto para compartilhar ou salvar.',
    backupExportError: 'Não foi possível gerar o arquivo de backup.',
    backupImportConfirmTitle: 'Restaurar Backup',
    backupImportConfirmMsg: 'Escolha como deseja restaurar o backup:\n\n• SUBSTITUIR: Sobrescreve completamente os dados atuais pelo backup.\n• MESCLAR: Combina os dados do backup sem apagar os existentes.',
    backupImportReplace: 'SUBSTITUIR (Sobrescrever)',
    backupImportMerge: 'MESCLAR (Combinar)',
    backupImportSuccess: 'Backup restaurado com sucesso! Banco de dados atualizado.',
    backupImportError: 'Não foi possível restaurar o backup. Verifique o formato do arquivo.',
    backupTipsTitle: 'Dicas de Backup e Segurança',
    protectDataLabel: 'Como proteger seus dados de repertório:',
    tip2: '• Faça backups manuais: Salve seus setlists mais importantes gerando os códigos de exportação com o botão de compartilhamento e guardando-os no WhatsApp ou bloco de notas.',
    tip3: '• Restaurar dados: Se precisar reinstalar o aplicativo ou trocar de aparelho, utilize a opção Importar na aba correspondente e cole o código ou selecione o arquivo para recuperar tudo instantaneamente.',
    backupAllBtn: 'BACKUP TOTAL',
    restoreBackupBtn: 'RESTAURAR BACKUP',
    restoreBackupTitle: 'RESTAURAR BACKUP',
    restoreBackupDesc: 'Selecione o arquivo de backup (.json) ou cole o código no editor abaixo para restaurar todos os dados.',
    backupCreatedAlert: 'Backup criado com sucesso!',
    codeCopied: 'e copiado para a área de transferência!',
    backupAllTitle: 'Backup Total de Dados',

    // Sobre o Aplicativo
    loadingDatabase: 'Carregando banco...',
    aboutTitle: 'SOBRE O SETLIST APP',
    aboutHeader: 'SOBRE',
    aboutTheApp: 'O Aplicativo',
    aboutAppDesc: 'O Setlist Band Manager é uma ferramenta profissional projetada para auxiliar músicos, bandas e produtores a organizarem seu repertório e seus roteiros de shows de forma impecável.',
    aboutFeatures: 'Funcionalidades Principais',
    aboutDev: 'DESENVOLVIDO POR:',
    version: 'Versão',
    versionText: 'Versão',
    developer: 'Desenvolvedor',
    developedBy: 'Desenvolvido com dedicação para músicos, bandas e artistas.',
    featuresTitle: 'FUNCIONALIDADES',
    feature1: 'Gestão completa de Setlists, Repertórios e Ensaios.',
    feature2: 'Modo Palco com rolagem automática e visualização de cifras.',
    feature3: 'Suporte multibandas com repertórios personalizados.',
    feature4: 'Exportação para Word (.doc), JSON e Backup Total.',
    feature5: 'Backup e Restauração completa para total segurança.',
    feature6: 'Suporte a múltiplos temas visuais e modo escuro.',
    aboutFeature1Title: 'Gestão Multibandas',
    aboutFeature1Desc: 'Cadastre suas bandas com foto/logo e gerencie os roteiros e repertórios de cada projeto.',
    aboutFeature2Title: 'Repertório Estruturado',
    aboutFeature2Desc: 'Guarde letras, cifras, tablaturas, duração e links de apoio de forma organizada.',
    aboutFeature3Title: 'Modo Palco',
    aboutFeature3Desc: 'Visualize cifras e letras em tela cheia com rolagem automática e letreiro dinâmico.',
    aboutFeature4Title: 'Ensaios Inteligentes',
    aboutFeature4Desc: 'Avalie o desempenho das músicas no ensaio com cores (verde/amarelo/vermelho), crie observações e salve tudo.',
    aboutFeature5Title: 'Compartilhamento, Exportação e Backup',
    aboutFeature5Desc: 'Exporte setlists em Word (.doc), compartilhe em JSON e faça backup e restauração total do banco de dados.',
    aboutFeature6Title: 'Multilíngue e Personalização',
    aboutFeature6Desc: 'Alterne o idioma entre Português, Inglês e Espanhol e escolha cores primárias e secundárias premium.',
    aboutFeature7Title: 'Fixados e Favoritos',
    aboutFeature7Desc: 'Marque setlists e músicas com estrela para mantê-los fixados no topo automaticamente.',
    aboutFeature8Title: 'Múltiplas Tags e Filtros',
    aboutFeature8Desc: 'Cadastre músicas com múltiplas tags por vírgula e filtre combinando até 3 tags simultâneas.',
    aboutFeature9Title: 'Reordenação por Arraste',
    aboutFeature9Desc: 'Organize a ordem das músicas no setlist arrastando de forma suave e rápida com física de mola e vibração.',
    aboutFeature10Title: 'Linhas de Anotação e Notas',
    aboutFeature10Desc: 'Adicione avisos, observações ou quebras de seção diretamente no setlist como telas de destaque no Modo Palco.',
    tutorialGuide: 'TUTORIAL PRÁTICO',
    tapForTutorial: 'TOQUE PARA O GUIA',
    stepByStep: 'COMO USAR PASSO A PASSO:',
    proTip: 'DICA DE OURO:',
    understood: 'ENTENDIDO',

    // Sincronização Web e Compartilhamento QR
    webEditorTitle: 'WEB EDITOR',
    webSyncSubtitle: 'Conecte ao seu computador (PC) ou outro celular via QR Code ou PIN',
    webSyncDesc: 'Transfira todo o seu repertório, letras, cifras e setlists entre o aplicativo do celular, o computador (PC) ou outro celular com apenas 1 leitura de câmera ou código PIN de 6 dígitos.',
    openSyncQrBtn: 'ABRIR SINCRONIZADOR QR CODE',
    syncModalTitle: 'Sincronizar & Compartilhar',
    syncModalSubtitle: 'Web Editor (PC) ou Outro Celular',
    connectedSuccess: 'Conectado com Sucesso!',
    chooseAction: 'Escolha a ação desejada:',
    sendToPcTitle: 'ENVIAR PARA PC',
    sendToPcDesc: 'Envia todas as músicas deste celular para o computador',
    pullFromPcTitle: 'PUXAR DO PC / CELULAR',
    pullFromPcDesc: 'Baixa o repertório compartilhado para este celular',
    scanAnotherCode: 'Escanear outro código',
    tabScanQr: 'Ler QR',
    tabGenerateQr: 'Gerar QR',
    tabPin: 'PIN',
    cameraPermRequired: 'Acesso à Câmera Necessário',
    cameraPermDesc: 'Para ler o QR Code no monitor do PC ou em outro celular, precisamos da permissão da câmera.',
    allowCameraBtn: 'Permitir Câmera',
    pointCameraInstruction: 'Aponte para o QR Code do PC ou do celular',
    preparingQrCode: 'Preparando repertório e gerando QR Code...',
    pinCodeLabel: 'CÓDIGO PIN:',
    qrInstruction: 'No outro aparelho, abra o app, vá em "Ler QR" e aponte a câmera para esta tela.',
    generateNewCode: 'Gerar Novo Código',
    shareWithNearbyPhone: 'Compartilhar com Celular Próximo',
    shareWithNearbyPhoneDesc: 'Gere um QR Code na tela para enviar todas as suas músicas e setlists diretamente para o aparelho de outro integrante da banda.',
    generateQrNowBtn: 'Gerar QR Code Agora',
    transferSuccessTitle: 'Sucesso! 🎉',
    transferSuccessMsg: 'Seu repertório foi transferido com sucesso para o outro celular!',
    enterPinTitle: 'Digite o PIN de 6 Dígitos',
    enterPinDesc: 'Código exibido na tela do PC ou do outro celular:',
    connectByPinBtn: 'Conectar e Importar',
    pullingData: 'Baixando repertório...',
    savingSongsLocally: 'Salvando músicas no celular...',
    repertoireReceivedTitle: 'Repertório Recebido! 🎉',
    repertoireReceivedMsg: 'Todas as músicas e setlists compartilhados foram importados e salvos no seu aparelho!',
    repertoireReceivedPinMsg: 'Músicas e setlists importados com sucesso via PIN!',
    invalidPinTitle: 'PIN Inválido',
    invalidPinMsg: 'Digite o código numérico de 6 dígitos.',
    connectingPin: 'Conectando ao código PIN...',
    sessionNotFoundTitle: 'Sessão Não Encontrada',
    sessionNotFoundMsg: 'Código PIN incorreto ou expirado.',
    collectingRepertoire: 'Coletando repertório e setlists...',
    transmittingToPc: 'Transmitindo dados para a tela do PC...',
    transmittedSuccessTitle: 'Sucesso! 🎉',
    transmittedSuccessMsg: 'Todos os dados foram transmitidos com sucesso para a tela do Web Editor no PC!',
    transmissionErrorTitle: 'Erro na Transmissão',
    transmissionErrorMsg: 'Não foi possível enviar os dados.',
    connectionErrorTitle: 'Erro de Conexão',
    connectionErrorMsg: 'Verifique sua conexão com a internet e tente novamente.',
    fetchingWebData: 'Buscando dados do Web Editor...',
    updatingDatabaseMsg: 'Atualizando banco de dados no celular...',
    syncCompletedTitle: 'Sincronização Concluída! 🚀',
    syncCompletedMsg: 'Todas as músicas e setlists editados no PC foram importados com sucesso para o seu celular!',
    awaitingDataTitle: 'Aguardando Dados',
    awaitingDataMsg: 'Nenhum dado foi enviado do PC ainda. No Web Editor, clique na aba "Enviar para o Celular".',
    invalidQrTitle: 'QR Code Inválido',
    invalidQrMsg: 'O código escaneado não pertence ao Setlist Band Manager.',
    processQrError: 'Não foi possível processar o QR Code.',
    sessionGenerateError: 'Não foi possível gerar a sessão de compartilhamento.',
    connectedToPin: 'Conectado ao PIN',
    connectedToSession: 'Conectado à Sessão',

    // Filtros e Tipos de Evento
    filterPrefix: 'FILTRO:',
    filterAll: 'TODAS',
    filterShows: 'SHOWS',
    filterRehearsals: 'ENSAIOS',
    filterRepertoire: 'REPERTÓRIO',
    allPlural: 'TODAS',
    ensaio: 'Ensaio',
    repertório: 'Repertório',
  },

  en: {
    // Navigation & Tabs
    home: 'Home',
    songs: 'Songs',
    setlists: 'Setlists',
    options: 'Options',
    about: 'About',

    // Common Actions & Dialogs
    confirm: 'Confirm',
    cancel: 'Cancel',
    save: 'SAVE',
    close: 'Close',
    closeBtn: 'CLOSE',
    edit: 'Edit',
    delete: 'Delete',
    copy: 'Duplicate',
    share: 'Share',
    exportWord: 'Export Word',
    exportPdf: 'PDF',
    generatingPdf: 'Generating PDF...',
    pdfSuccess: 'PDF created successfully!',
    pdfError: 'Could not generate PDF.',
    exportDocSuccess: 'Document exported successfully!',
    shareTitle: 'Share',
    sharePrompt: 'Choose format:',
    shareAsFile: 'Physical File (.json)',
    shareAsFileDesc: 'Ideal for sending to other app users to import.',
    shareAsText: 'Formatted Text',
    shareAsTextDesc: 'Ideal for sending via WhatsApp, Telegram, etc.',
    shareSuccess: 'Shared successfully!',
    shareOptionJson: 'File (.json)',
    shareOptionQr: 'Generate QR Code',
    shareOptionText: 'Formatted Text',
    shareOptionsTitle: 'Share',
    shareOptionsSubtitle: 'Choose how you want to share:',
    shareQrTitle: 'Share via QR Code',
    shareQrDesc: 'Transfer directly to another phone via camera or PIN code.',
    shareJsonTitle: 'Physical File (.json)',
    shareJsonDesc: 'Generate .json file to send on WhatsApp or backup.',
    shareTextTitle: 'Formatted Text',
    shareTextDesc: 'Send structured readable text with song and chords.',
    shareSongLabel: 'Song',
    shareSetlistLabel: 'Setlist',
    shareQrModalTitleSong: 'Share Song via QR',
    shareQrModalTitleSetlist: 'Share Setlist via QR',
    shareQrInstruction: 'Point the other phone camera at Sync ➔ Scan QR (or type the PIN) to import this item instantly!',
    shareQrPinLabel: 'PIN CODE',
    generatingItemQr: 'Generating sharing QR Code...',
    itemTransferSuccessTitle: 'Transfer Completed! 🎉',
    itemTransferSuccessMsg: 'The item was transferred and imported successfully to the other device!',
    songImportedSuccess: 'Song "{name}" imported successfully!',
    setlistImportedSuccess: 'Setlist "{name}" imported successfully!',
    importOptionsTitle: 'Import',
    importOptionsSubtitle: 'Choose how you want to import:',
    importSongSubtitle: 'Add a new song to your repertoire',
    importSetlistSubtitle: 'Import a gig or rehearsal setlist',
    restoreBackupSubtitle: 'Restore full application database',
    importOptionQrTitle: 'Scan QR Code (Camera or PIN)',
    importOptionQrDesc: 'Point camera at another phone/PC QR code or type PIN.',
    importOptionFileTitle: 'Select File (.json)',
    importOptionFileDesc: 'Open a .json file saved on your device or WhatsApp.',
    importOptionTextTitle: 'Paste Code / JSON Text',
    importOptionTextDesc: 'Paste copied code or text into the text editor.',
    search: 'Search...',
    searchPlaceholder: 'Search...',
    searchPlaceholderDesc: 'Search by title, artist, or style...',
    emptyState: 'No records found.',
    attention: 'Attention',
    success: 'Success',
    info: 'Information',
    optionsBtn: 'Options',
    optionsTitle: 'Options',
    done: 'DONE',

    // Home Tab
    myBands: 'My Bands',
    quickStats: 'QUICK STATISTICS',
    totalSongs: 'Total Songs',
    totalSetlists: 'Total Setlists',
    noBands: 'No bands registered yet. Click "+ Band" at the top to create one!',
    noSongs: 'No songs found. Click "+ Song" at the top to register one!',
    upcomingEvents: 'UPCOMING EVENTS',
    pastEvents: 'PAST',
    sortBy: 'SORT BY:',
    band: 'Band',
    song: 'Song',
    since: 'Since',
    until: 'until',
    cachet: 'Cachet',
    accumulated: 'Total',
    createBandBtn: '+ Create Band',
    createEventBtn: '+ Create Event',
    noBandsYet: 'No bands registered',
    noBandsSubtitle: 'Click "+ Band" at the top to add your musical project.',
    searchRepertoire: 'Search repertoire...',
    noSongsInRepertoire: 'No songs in repertoire',
    bandSongsSubtitle: 'Songs linked to this band will appear here.',
    addMember: 'Add Member',
    activeMembers: 'ACTIVE MEMBERS',
    noMembersYet: 'No members added yet',
    hideInactiveMembers: 'Hide Inactive Members',
    showInactiveMembers: 'Show Inactive Members',
    newEntry: 'New Entry',
    editEntry: 'Edit Entry',
    noShowsForBand: 'No shows registered for this band yet.',
    untitledShow: 'Untitled Show',
    noLocationSpecified: 'Location not specified',
    showCachet: 'SHOW CACHET',
    toBeDefined: 'TO BE DEFINED',
    otherFinances: 'Others',
    income: 'INCOME',
    expense: 'EXPENSE',
    newEvent: 'New Event',
    noEventsScheduled: 'No events scheduled',
    bandEventsSubtitle: 'Shows and rehearsals for this band will appear here.',
    linkCollectionSongs: 'Link Songs from Collection',
    searchCollectionSong: 'Search song from collection...',
    descriptionLabel: 'Description: *',
    amountLabel: 'AMOUNT ($): *',
    entryTypeLabel: 'ENTRY TYPE:',
    today: 'Today',
    newMember: 'New Member',
    editMember: 'Edit Member',
    memberNameLabel: 'Name: *',
    memberRoleLabel: 'Role / Instrument (comma separated):',
    memberPhoneLabel: 'Contact (WhatsApp):',
    startDateLabel: 'Start Date:',
    endDateLabel: 'End Date:',
    memberStatusLabel: 'Member Status:',
    active: 'Active',
    inactive: 'Inactive',
    saveMember: 'Save Member',
    organizeRepertoire: 'Organize Repertoire',
    songNameAsc: 'Song Title (A - Z)',
    songNameDesc: 'Song Title (Z - A)',
    bandNameAsc: 'Original Band (A - Z)',
    bandNameDesc: 'Original Band (Z - A)',
    unsavedChangesMsg: 'You have unsaved changes. Do you want to save before leaving?',
    discard: 'Discard',
    leaveWithoutSaving: 'Leave without Saving',
    saveAndLeave: 'Save and Leave',
    tapToChange: 'Tap to change',
    untilCapital: 'Until',
    current: 'Current',
    startDateFormLabel: 'START DATE (DAY/MONTH/YEAR)',
    endDateFormLabel: 'END DATE (OPTIONAL)',
    cacheSplitTitle: 'Cachet Split per Member',
    totalCachet: 'Total Cachet:',
    divideEqually: 'Divide Equally',
    noActiveMembersBand: 'No active members registered in this band.',
    saveSplit: 'Save Split',
    noActiveMembers: 'No active members registered.',
    repertoireStyles: 'Repertoire Styles',
    noStyleTags: 'No style tags defined in this band\'s songs.',
    financialSummary: 'Financial Summary',
    incomes: 'Incomes',
    expenses: 'Expenses',
    balance: 'Balance',
    myBandsCarouselSubtitle: 'My Bands (Long press to edit/delete)',
    allBands: 'All Bands',
    showingAllBands: 'Showing all bands',
    showingBandSetlist: 'Showing setlists for',
    showingBandSongs: 'Showing songs for',
    viewAllBands: 'View all bands',

    // Band Management
    bands: 'Bands / Projects',
    addBand: '+ Band',
    newBand: 'NEW BAND',
    editBand: 'EDIT BAND',
    bandNameLabel: 'BAND NAME *',
    coverImageLabel: 'COVER IMAGE (OPTIONAL)',
    imageSelected: 'Image Selected',
    chooseImage: 'Choose Image from Gallery',
    removeImage: 'Remove Image',
    saveChanges: 'SAVE CHANGES',
    createBand: 'CREATE NEW BAND',
    deleteBandConfirmTitle: 'Delete Band',
    deleteBandConfirmMsg: 'Are you sure you want to delete the band "{name}"? Linked setlists will have their band field cleared.',
    deleteBandError: 'Could not delete the band.',
    noBand: 'No Band',

    // Song Management
    addSong: '+ Song',
    newSong: 'NEW SONG',
    editSong: 'EDIT SONG',
    songNameLabel: 'SONG NAME *',
    songNamePlaceholder: 'Title',
    originalBandLabel: 'ORIGINAL BAND *',
    originalBandPlaceholder: 'Band',
    lyricsPlaceholder: 'Paste or type the lyrics here...',
    chordsPlaceholder: 'Paste or type the chords here (e.g., [C] [G] [Am] [F])...',
    tabsPlaceholder: 'Paste or type the tab here (e.g., e|---0---1---0---|)...',
    tagsPlaceholder: 'e.g. Rock, Pop, 80s',
    durationPlaceholder: 'e.g. 03:45',
    tagsLabel: 'TAGS ( , )',
    durationLabel: 'DURATION (MM:SS)',
    lyricsLabel: 'Lyrics',
    chordsLabel: 'Chords',
    tabsLabel: 'Tabs',
    lyricsFormLabel: 'Lyrics',
    chordsFormLabel: 'Chords',
    tabsFormLabel: 'Tabs',
    defaultViewLabel: 'DEFAULT VIEW',
    scrollSpeedLabel: 'SCROLL SPEED',
    defaultScrollSpeed: 'DEFAULT SCROLL SPEED (AUTOSCROLL)',
    supportLinks: 'SUPPORT LINKS',
    songDetails: 'SONG DETAILS',
    cifras: 'Chords',
    addLink: 'Add New Link',
    removeLink: 'Remove Link',
    invalidDurationTitle: 'Invalid Duration',
    invalidDurationMsg: 'Please enter duration in MM:SS format (e.g. 03:45) or leave blank.',
    editSongContent: 'EDIT SONG CONTENT',
    disabledLabel: 'Disabled',
    saveSong: 'SAVE SONG',
    alertSongName: 'Please enter the song name.',
    alertOriginalBand: 'Please enter the original band.',
    deleteSongConfirmTitle: 'Delete Song',
    deleteSongConfirmMsg: 'Are you sure you want to delete this song from the global database?',
    deleteSongError: 'Could not delete the song.',
    songAlreadyExists: 'The song "{name}" already exists in the database and was not duplicated.',
    songsBadge: 'songs',
    tagAll: 'All Tags',
    filterByTag: 'Filter by Tag',
    filterByStatus: 'Filter by Status',
    allStatuses: 'All',
    songInfoBpm: 'BPM',
    songInfoCapo: 'Capo',
    songInfoKey: 'Key',

    songSingular: 'song',
    songPlural: 'songs',

    // Setlist Management
    addSetlist: '+ Setlist',
    newSetlist: 'NEW SETLIST',
    editSetlist: 'EDIT SETLIST',
    presentationType: 'EVENT TYPE',
    show: 'Show',
    rehearsal: 'Rehearsal',
    repertoire: 'Repertoire',
    responsibleBand: 'RESPONSIBLE BAND *',
    registerBandFirst: 'Register at least one band before creating a setlist.',
    setlistNameLabel: 'SETLIST NAME *',
    setlistNamePlaceholder: 'Event Name',
    addSongBtn: '+ Song',
    addPauseBtn: '+ Pause',
    addNoteBtn: '+ Note',
    datePlaceholder: 'YYYY-MM-DD',
    localPlaceholder: 'e.g. Joe\'s Bar, Studio X...',
    cachetPlaceholder: 'e.g. 500',
    dateLabel: 'DATE *',
    localLabel: 'LOCATION',
    cachêLabel: 'Cachet',
    notesLabel: 'EVENT NOTES',
    selectAll: 'Select All',
    deselectAll: 'Deselect All',
    selectedSongsCount: 'selected',
    noSongsCollection: 'No songs found in collection.',
    saveRepertoire: 'Save Repertoire',
    linkCollectionSongs: 'COLLECTION SONGS',
    searchCollectionSong: 'Search collection...',
    addSelectedCount: 'ADD SELECTED',
    dragToReorderTip: 'Drag ☰ to reorder',
    swipeToDeleteTip: 'Swipe left to delete',
    pauseItem: 'PAUSE',
    editPauseTitle: 'EDIT PAUSE',
    editNoteTitle: 'EDIT NOTE',
    typeNotePrompt: 'Type your note or message...',
    durationExamplePlaceholder: 'e.g. 5 min, 10 min',
    foundPlural: 'found',
    copySetlistBtn: 'Copy Setlist',
    setlistCopiedMsg: 'Setlist copied successfully!',
    setlistCopyError: 'Could not duplicate setlist.',
    availableSongs: 'AVAILABLE SONGS',
    songsLabel: 'AVAILABLE SONGS',
    reorderBtn: 'REORDER',
    reorderTitle: 'REORDER SETLIST',
    reorderHelp: 'Drag by the ☰ icon to reorder. Tap X to remove.',
    reorderTip: 'Tap a song to select it, then tap another position to move it instantly.',
    reorderTipDrag: 'Drag songs by holding the handle (☰) on the right to reorder smoothly.',
    selectedSongsLabel: 'SELECTED SONGS (DRAG TO REORDER)',
    createSetlist: 'CREATE SETLIST',
    noteItem: 'NOTE',
    notePlaceholder: 'Type notes for this event or performance...',
    alertSetlistName: 'Please enter the setlist name.',
    alertSelectBand: 'Please select an associated band.',
    alertSetlistDate: 'Please enter the setlist date.',
    alertSelectSong: 'Please select at least one song for the setlist.',
    alertSelectSongOrPauseFirst: 'Select a song or pause first.',
    deleteSetlistConfirmTitle: 'Delete Setlist',
    deleteSetlistConfirmMsg: 'Are you sure you want to delete this setlist?',
    deleteSetlistError: 'Could not delete the setlist.',
    addToSetlist: 'ADD TO SETLIST',
    noSongsInSetlist: 'No songs selected for this setlist yet.',
    reorderDoneBtn: 'DONE',

    // Multi-Select Song Picker
    addSongsBtn: 'ADD SONGS',
    selectSongsModalTitle: 'SELECT SONGS',
    selectAll: 'Select All',
    deselectAll: 'Deselect All',
    addSelectedCount: 'ADD SELECTED',
    selectedCount: 'selected',
    noSongsFoundInPicker: 'No songs found.',

    // Setlist Card & Detail Modal
    dateText: 'Date',
    localText: 'Venue',
    cachêText: 'Cachet',
    cacheText: 'Cachet',
    notesText: 'Notes',
    typeText: 'Type',
    songsCount: 'Songs',
    songsTitle: 'SETLIST SONGS',
    estimatedTime: 'Estimated Time',
    venue: 'Venue',
    noSongsInCard: 'No setlists found for active filters.',
    noSongsInDetail: 'No songs associated with this setlist.',
    detailTitle: 'SETLIST DETAILS',
    startStage: 'Stage',
    startStageBtn: 'STAGE MODE',
    setlistTabRepertoire: 'REPERTOIRE',
    setlistTabDetails: 'EVENT DETAILS',
    editNoteTitle: 'EDIT NOTE',
    editPauseTitle: 'EDIT PAUSE',
    duplicateSetlist: 'Duplicate Setlist',
    createCopy: 'Create Copy',
    showsAndCaches: 'Show Gigs & Cachets',
    noCachetDefined: 'No Cachet registered',
    nextEventHero: 'UPCOMING EVENT',
    membersBadge: 'members',
    tapToEditSongTip: 'Tap song to edit chords/lyrics',
    dragToReorderTip: 'Drag by ☰ icon to reorder',
    swipeToDeleteTip: 'Swipe left to delete',
    rehearsalNotesPlaceholder: 'Rehearsal notes (optional)',

    // Stage Performance Mode
    pause: 'PAUSE',
    pauseTitle: 'PAUSE / BREAK',
    note: 'NOTE',
    noteTitle: 'NOTE / ANNOTATION',
    rehearsalReport: 'FULL SETLIST',
    noLyrics: 'No lyrics registered for this song.',
    noChords: 'No chords registered for this song.',
    noTabs: 'No tabs registered for this song.',
    noContentRegistered: 'No content registered for this song.',
    timerCountdown: 'Countdown',
    timerPaused: 'Paused',
    timerFinished: 'PAUSE FINISHED!',
    timerNoLimit: 'NO TIME LIMIT',
    pauseTimer: 'PAUSE TIMER',
    startTimer: 'START TIMER',
    resetTimer: 'RESET',
    closeList: 'CLOSE LIST',

    // Import Modal
    importBtnText: 'Import',
    importTitle: 'IMPORT DATA',
    importTitleSetlist: 'IMPORT SETLIST',
    importTitleSong: 'IMPORT SONG',
    importDescSetlist: 'Select the setlist file (.json) or paste the code in the editor below to import.',
    importDescSong: 'Select the song file (.json) or paste the code in the editor below to import.',
    fileTypeLabelSong: 'song',
    fileTypeLabelSetlist: 'setlist',
    fileTypeLabelBackup: 'backup',
    pasteJsonLabel: 'PASTE JSON CODE HERE',
    importBtn: 'IMPORT DATA',
    importNow: 'IMPORT NOW',
    selectFileLabel: 'SELECT JSON FILE',
    orPasteCode: 'OR PASTE TEXT CODE',
    importSuccessSong: 'Song imported successfully!',
    importSuccessSetlist: 'Setlist imported successfully!',
    importErrorTitle: 'Import Error',
    importErrorMsg: 'Could not import data. Please check JSON formatting.',
    invalidJsonMsg: 'Pasted code is not a valid JSON.',
    fileLoadedAlert: 'File loaded! Click IMPORT NOW to finish.',
    fileReadError: 'Could not read the selected file.',

    // Theme & Appearance
    themeAppearance: 'THEME & APPEARANCE',
    themeMode: 'THEME MODE',
    dark: 'Dark',
    light: 'Light',
    primaryColor: 'PRIMARY COLOR',
    secondaryColor: 'SECONDARY COLOR',
    appLanguage: 'APP LANGUAGE',

    // Backup & Restore
    backupSectionTitle: 'BACKUP & RESTORE',
    backupSubtitle: 'Export or import your entire app database (bands, songs, setlists) safely.',
    backupExportBtn: 'FULL BACKUP (EXPORT)',
    backupImportBtn: 'RESTORE BACKUP (IMPORT)',
    backupExportSuccess: 'Backup exported successfully! File ready to share or save.',
    backupExportError: 'Could not generate backup file.',
    backupImportConfirmTitle: 'Restore Backup',
    backupImportConfirmMsg: 'Choose how you want to restore the backup:\n\n• REPLACE: Completely overwrites existing data with the backup.\n• MERGE: Combines backup data without deleting existing ones.',
    backupImportReplace: 'REPLACE (Overwrite)',
    backupImportMerge: 'MERGE (Combine)',
    backupImportSuccess: 'Backup restored successfully! Database updated.',
    backupImportError: 'Could not restore backup file. Please check file format.',
    backupTipsTitle: 'Backup & Security Tips',
    protectDataLabel: 'How to protect your repertoire data:',
    tip2: '• Make manual backups: Save your most important setlists by generating export codes or JSON files with the share button and keeping them in WhatsApp or notes.',
    tip3: '• Restore data: If you need to reinstall the app or change devices, use the Import option in the corresponding tab and paste the code or select the file to recover everything instantly.',
    backupAllBtn: 'TOTAL BACKUP',
    restoreBackupBtn: 'RESTORE BACKUP',
    restoreBackupTitle: 'RESTORE BACKUP',
    restoreBackupDesc: 'Select the backup file (.json) or paste the code in the editor below to restore all data.',
    backupCreatedAlert: 'Backup created successfully!',
    codeCopied: 'and copied to clipboard!',
    backupAllTitle: 'Total Data Backup',

    // About The App
    loadingDatabase: 'Loading database...',
    aboutTitle: 'ABOUT SETLIST APP',
    aboutHeader: 'ABOUT',
    aboutTheApp: 'The App',
    aboutAppDesc: 'Setlist Band Manager is a professional tool designed to help musicians, bands, and producers organize their repertoire and setlists flawlessly.',
    aboutFeatures: 'Key Features',
    aboutDev: 'DEVELOPED BY:',
    version: 'Version',
    versionText: 'Version',
    developer: 'Developer',
    developedBy: 'Developed with dedication for musicians, bands, and artists.',
    featuresTitle: 'FEATURES',
    feature1: 'Full management of Setlists, Repertoires, and Rehearsals.',
    feature2: 'Stage Performance Mode with auto-scroll and chords.',
    feature3: 'Multi-band support with customized repertoires.',
    feature4: 'Export to Word (.doc), JSON and Full Backup.',
    feature5: 'Full Backup & Restore for total data safety.',
    feature6: 'Support for multiple visual themes and dark mode.',
    aboutFeature1Title: 'Multi-band Management',
    aboutFeature1Desc: 'Register your bands with photo/logo and manage setlists and repertoires for each project.',
    aboutFeature2Title: 'Structured Repertoire',
    aboutFeature2Desc: 'Keep lyrics, chords, tabs, duration, and reference links neatly organized.',
    aboutFeature3Title: 'Stage Mode',
    aboutFeature3Desc: 'View chords and lyrics in full-screen with auto-scroll and dynamic stage marquee.',
    aboutFeature4Title: 'Smart Rehearsals',
    aboutFeature4Desc: 'Rate song performance in rehearsals with colors (green/yellow/red), create notes, and save history.',
    aboutFeature5Title: 'Sharing, Exporting & Backup',
    aboutFeature5Desc: 'Export setlists to Word (.doc), share via JSON, and perform full database backup and restore.',
    aboutFeature6Title: 'Multilingual & Themes',
    aboutFeature6Desc: 'Switch language between Portuguese, English, and Spanish and customize appearance with premium theme colors.',
    aboutFeature7Title: 'Pinned & Favorites',
    aboutFeature7Desc: 'Mark setlists and songs with a star to keep them automatically pinned at the top.',
    aboutFeature8Title: 'Multiple Tags & Filters',
    aboutFeature8Desc: 'Register songs with multiple tags separated by comma and filter combining up to 3 tags simultaneously.',
    aboutFeature9Title: 'Drag-and-Drop Reordering',
    aboutFeature9Desc: 'Reorganize setlist song order by dragging smoothly and quickly with physics and haptic feedback.',
    aboutFeature10Title: 'Setlist Notes & Observations',
    aboutFeature10Desc: 'Add notices, observations, or section breaks inside the setlist, showing as highlight screens in Stage Mode.',
    tutorialGuide: 'PRACTICAL TUTORIAL',
    tapForTutorial: 'TAP FOR GUIDE',
    stepByStep: 'STEP-BY-STEP GUIDE:',
    proTip: 'PRO TIP:',
    understood: 'UNDERSTOOD',

    // Web Sync & QR Share
    webEditorTitle: 'WEB EDITOR',
    webSyncSubtitle: 'Connect to your PC or another phone via QR Code or PIN',
    webSyncDesc: 'Transfer your entire repertoire, lyrics, chords, and setlists between your phone, PC, or another mobile phone using a single camera QR scan or 6-digit PIN code.',
    openSyncQrBtn: 'OPEN QR CODE SYNC',
    syncModalTitle: 'Sync & Share',
    syncModalSubtitle: 'Web Editor (PC) or Another Phone',
    connectedSuccess: 'Connected Successfully!',
    chooseAction: 'Choose desired action:',
    sendToPcTitle: 'SEND TO PC',
    sendToPcDesc: 'Send all songs from this phone to PC',
    pullFromPcTitle: 'PULL FROM PC / MOBILE',
    pullFromPcDesc: 'Download shared repertoire to this phone',
    scanAnotherCode: 'Scan another code',
    tabScanQr: 'Scan QR',
    tabGenerateQr: 'Generate QR',
    tabPin: 'PIN',
    cameraPermRequired: 'Camera Access Required',
    cameraPermDesc: 'To scan QR Codes on PC screen or another phone, camera permission is required.',
    allowCameraBtn: 'Allow Camera',
    pointCameraInstruction: 'Point at the QR Code on PC or phone',
    preparingQrCode: 'Preparing repertoire and generating QR Code...',
    pinCodeLabel: 'PIN CODE:',
    qrInstruction: 'On the other device, open the app, tap "Scan QR" and point the camera at this screen.',
    generateNewCode: 'Generate New Code',
    shareWithNearbyPhone: 'Share with Nearby Phone',
    shareWithNearbyPhoneDesc: 'Generate a QR Code on screen to send all your songs and setlists directly to another band member\'s device.',
    generateQrNowBtn: 'Generate QR Code Now',
    transferSuccessTitle: 'Success! 🎉',
    transferSuccessMsg: 'Your repertoire was transferred successfully to the other phone!',
    enterPinTitle: 'Enter 6-Digit PIN',
    enterPinDesc: 'Code displayed on PC screen or the other phone:',
    connectByPinBtn: 'Connect & Import',
    pullingData: 'Downloading repertoire...',
    savingSongsLocally: 'Saving songs to phone...',
    repertoireReceivedTitle: 'Repertoire Received! 🎉',
    repertoireReceivedMsg: 'All shared songs and setlists have been imported and saved on your device!',
    repertoireReceivedPinMsg: 'Songs and setlists imported successfully via PIN!',
    invalidPinTitle: 'Invalid PIN',
    invalidPinMsg: 'Please enter the 6-digit numeric PIN.',
    connectingPin: 'Connecting to PIN code...',
    sessionNotFoundTitle: 'Session Not Found',
    sessionNotFoundMsg: 'Incorrect or expired PIN code.',
    collectingRepertoire: 'Collecting repertoire and setlists...',
    transmittingToPc: 'Transmitting data to PC screen...',
    transmittedSuccessTitle: 'Success! 🎉',
    transmittedSuccessMsg: 'All data was transferred successfully to Web Editor on PC!',
    transmissionErrorTitle: 'Transmission Error',
    transmissionErrorMsg: 'Could not send data.',
    connectionErrorTitle: 'Connection Error',
    connectionErrorMsg: 'Check your internet connection and try again.',
    fetchingWebData: 'Fetching data from Web Editor...',
    updatingDatabaseMsg: 'Updating local database on phone...',
    syncCompletedTitle: 'Sync Completed! 🚀',
    syncCompletedMsg: 'All songs and setlists edited on PC have been imported to your phone!',
    awaitingDataTitle: 'Awaiting Data',
    awaitingDataMsg: 'No data sent from PC yet. In Web Editor, click "Send to Mobile".',
    invalidQrTitle: 'Invalid QR Code',
    invalidQrMsg: 'The scanned code does not belong to Setlist Band Manager.',
    processQrError: 'Could not process QR Code.',
    sessionGenerateError: 'Could not generate sharing session.',
    connectedToPin: 'Connected to PIN',
    connectedToSession: 'Connected to Session',

    // Setlist Filters & Event Types
    filterPrefix: 'FILTER:',
    filterAll: 'ALL',
    filterShows: 'SHOWS',
    filterRehearsals: 'REHEARSALS',
    filterRepertoire: 'REPERTOIRE',
    allPlural: 'ALL',
    ensaio: 'Rehearsal',
    repertório: 'Repertoire',
  },

  es: {
    // Navegación y Pestañas
    home: 'Inicio',
    songs: 'Canciones',
    setlists: 'Setlists',
    options: 'Opciones',
    about: 'Acerca de',

    // Acciones Generales y Diálogos
    confirm: 'Confirmar',
    cancel: 'Cancelar',
    save: 'GUARDAR',
    close: 'Cerrar',
    closeBtn: 'CERRAR',
    edit: 'Editar',
    delete: 'Eliminar',
    copy: 'Duplicar',
    share: 'Compartir',
    exportWord: 'Exportar Word',
    exportPdf: 'PDF',
    generatingPdf: 'Generando PDF...',
    pdfSuccess: '¡PDF creado con éxito!',
    pdfError: 'No se pudo generar el PDF.',
    exportDocSuccess: '¡Documento exportado con éxito!',
    shareTitle: 'Compartir',
    sharePrompt: 'Elija el formato:',
    shareAsFile: 'Archivo (.json)',
    shareAsFileDesc: 'Ideal para enviar a otros usuarios de la app para importar.',
    shareAsText: 'Texto con Formato',
    shareAsTextDesc: 'Ideal para enviar por WhatsApp, Telegram, etc.',
    shareSuccess: '¡Compartido con éxito!',
    shareOptionJson: 'Archivo (.json)',
    shareOptionQr: 'Generar Código QR',
    shareOptionText: 'Texto con Formato',
    shareOptionsTitle: 'Compartir',
    shareOptionsSubtitle: 'Elija cómo desea compartir:',
    shareQrTitle: 'Compartir vía Código QR',
    shareQrDesc: 'Transfiera directo a otro móvil con la cámara o código PIN.',
    shareJsonTitle: 'Archivo Físico (.json)',
    shareJsonDesc: 'Genere el archivo .json para WhatsApp o respaldo.',
    shareTextTitle: 'Texto con Formato',
    shareTextDesc: 'Envíe datos estructurados con acordes y letra.',
    shareSongLabel: 'Canción',
    shareSetlistLabel: 'Setlist',
    shareQrModalTitleSong: 'Compartir Canción vía QR',
    shareQrModalTitleSetlist: 'Compartir Setlist vía QR',
    shareQrInstruction: '¡Apunte la cámara del otro teléfono en Sincronizar ➔ Escanear QR (o escriba el PIN) para importar este elemento al instante!',
    shareQrPinLabel: 'CÓDIGO PIN',
    generatingItemQr: 'Generando código QR de compartir...',
    itemTransferSuccessTitle: '¡Transferencia Completa! 🎉',
    itemTransferSuccessMsg: '¡El elemento se transfirió e importó con éxito en el otro dispositivo!',
    songImportedSuccess: '¡Canción "{name}" importada con éxito!',
    setlistImportedSuccess: '¡Setlist "{name}" importado con éxito!',
    importOptionsTitle: 'Importar',
    importOptionsSubtitle: 'Elija cómo desea importar:',
    importSongSubtitle: 'Añada una nueva canción a su repertorio',
    importSetlistSubtitle: 'Importe un repertorio de show o ensayo',
    restoreBackupSubtitle: 'Restaure datos completos de la app',
    importOptionQrTitle: 'Escanear Código QR (Cámara o PIN)',
    importOptionQrDesc: 'Apunte la cámara al QR de otro móvil/PC o escriba el PIN.',
    importOptionFileTitle: 'Seleccionar Archivo (.json)',
    importOptionFileDesc: 'Abra un archivo .json guardado en su dispositivo o WhatsApp.',
    importOptionTextTitle: 'Pegar Código / Texto JSON',
    importOptionTextDesc: 'Pegue el código o texto copiado en el editor de texto.',
    search: 'Buscar...',
    searchPlaceholder: 'Buscar...',
    searchPlaceholderDesc: 'Buscar por título, artista o estilo...',
    emptyState: 'No se encontraron registros.',
    attention: 'Atención',
    success: 'Éxito',
    info: 'Información',
    optionsBtn: 'Opciones',
    optionsTitle: 'Opciones',
    done: 'CONCLUIDO',

    // Pestaña Inicio (Home)
    myBands: 'Mis Bandas',
    quickStats: 'ESTADÍSTICAS RÁPIDAS',
    totalSongs: 'Total de Canciones',
    totalSetlists: 'Total de Setlists',
    noBands: '¡Ninguna banda registrada aún! Haga clic en "+ Banda" arriba para crear una.',
    noSongs: '¡Ninguna canción encontrada! Haga clic en "+ Canción" arriba para registrar una.',
    upcomingEvents: 'PRÓXIMOS EVENTOS',
    pastEvents: 'ANTIGUAS',
    sortBy: 'ORDENAR POR:',
    band: 'Banda',
    song: 'Canción',
    since: 'Desde',
    until: 'hasta',
    cachet: 'Pago',
    accumulated: 'Acumulado',
    createBandBtn: '+ Crear Banda',
    createEventBtn: '+ Crear Evento',
    noBandsYet: 'Ninguna banda registrada',
    noBandsSubtitle: 'Haga clic en "+ Banda" arriba para añadir su proyecto musical.',
    searchRepertoire: 'Buscar en el repertorio...',
    noSongsInRepertoire: 'Ninguna canción en el repertorio',
    bandSongsSubtitle: 'Las canciones vinculadas a esta banda aparecerán aquí.',
    addMember: 'Añadir Integrante',
    activeMembers: 'INTEGRANTES ACTIVOS',
    noMembersYet: 'Sin integrantes aún',
    hideInactiveMembers: 'Ocultar Integrantes Inactivos',
    showInactiveMembers: 'Mostrar Integrantes Inactivos',
    newEntry: 'Nuevo Registro',
    editEntry: 'Editar Registro',
    noShowsForBand: 'Ningún show registrado para esta banda aún.',
    untitledShow: 'Show Sin Nombre',
    noLocationSpecified: 'Lugar no especificado',
    showCachet: 'PAGO DE SHOW',
    toBeDefined: 'A DEFINIR',
    otherFinances: 'Otros',
    income: 'INGRESO',
    expense: 'GASTO',
    newEvent: 'Nuevo Evento',
    noEventsScheduled: 'Ningún evento programado',
    bandEventsSubtitle: 'Los shows y ensayos de esta banda aparecerán aquí.',
    linkCollectionSongs: 'Vincular Canciones de la Colección',
    searchCollectionSong: 'Buscar canción de la colección...',
    descriptionLabel: 'Descripción: *',
    amountLabel: 'VALOR ($): *',
    entryTypeLabel: 'TIPO DE REGISTRO:',
    today: 'Hoy',
    newMember: 'Nuevo Integrante',
    editMember: 'Editar Integrante',
    memberNameLabel: 'Nombre: *',
    memberRoleLabel: 'Función / Instrumento (separados por coma):',
    memberPhoneLabel: 'Contacto (WhatsApp):',
    startDateLabel: 'Fecha Inicio:',
    endDateLabel: 'Fecha Fin:',
    memberStatusLabel: 'Estado del Integrante:',
    active: 'Activo',
    inactive: 'Inactivo',
    saveMember: 'Guardar Integrante',
    organizeRepertoire: 'Organizar Repertorio',
    songNameAsc: 'Nombre de Canción (A - Z)',
    songNameDesc: 'Nombre de Canción (Z - A)',
    bandNameAsc: 'Banda Original (A - Z)',
    bandNameDesc: 'Banda Original (Z - A)',
    unsavedChangesMsg: 'Tienes cambios sin guardar. ¿Deseas guardar antes de salir?',
    discard: 'Descartar',
    leaveWithoutSaving: 'Salir sin Guardar',
    saveAndLeave: 'Guardar y Salir',
    tapToChange: 'Toca para cambiar',
    untilCapital: 'Hasta',
    current: 'Actual',
    startDateFormLabel: 'FECHA DE INICIO (DÍA/MES/AÑO)',
    endDateFormLabel: 'FECHA FIN (OPCIONAL)',
    cacheSplitTitle: 'División de Pago por Integrante',
    totalCachet: 'Pago Total:',
    divideEqually: 'Dividir Igual',
    noActiveMembersBand: 'Ningún integrante activo registrado en esta banda.',
    saveSplit: 'Guardar División',
    noActiveMembers: 'Ningún integrante activo registrado.',
    repertoireStyles: 'Estilos del Repertorio',
    noStyleTags: 'Ninguna etiqueta de estilo definida en las canciones de esta banda.',
    financialSummary: 'Resumen Financiero',
    incomes: 'Ingresos',
    expenses: 'Gastos',
    balance: 'Saldo',
    myBandsCarouselSubtitle: 'Mis Bandas (Mantén presionado para editar/eliminar)',
    allBands: 'Todas las Bandas',
    showingAllBands: 'Mostrando todas las bandas',
    showingBandSetlist: 'Mostrando setlists de',
    showingBandSongs: 'Mostrando canciones de',
    viewAllBands: 'Ver todas las bandas',

    // Gestión de Bandas
    bands: 'Bandas / Proyectos',
    addBand: '+ Banda',
    newBand: 'NUEVA BANDA',
    editBand: 'EDITAR BANDA',
    bandNameLabel: 'NOMBRE DE LA BANDA *',
    coverImageLabel: 'FOTO DE PORTADA (OPCIONAL)',
    imageSelected: 'Imagen Seleccionada',
    chooseImage: 'Elegir Imagen de la Galería',
    removeImage: 'Eliminar Imagen',
    saveChanges: 'GUARDAR CAMBIOS',
    createBand: 'CREAR NUEVA BANDA',
    deleteBandConfirmTitle: 'Eliminar Banda',
    deleteBandConfirmMsg: '¿Está seguro de que desea eliminar la banda "{name}"? Los setlists vinculados tendrán su campo de banda borrado.',
    deleteBandError: 'No se pudo eliminar la banda.',
    noBand: 'Sin Banda',

    // Gestión de Canciones
    addSong: '+ Canción',
    newSong: 'NUEVA CANCIÓN',
    editSong: 'EDITAR CANCIÓN',
    songNameLabel: 'NOMBRE DE LA CANCIÓN *',
    songNamePlaceholder: 'Nombre',
    originalBandLabel: 'BANDA ORIGINAL *',
    originalBandPlaceholder: 'Banda',
    lyricsPlaceholder: 'Pegue o escriba la letra aquí...',
    chordsPlaceholder: 'Pegue o escriba los acordes aquí (ej: [C] [G] [Am] [F])...',
    tabsPlaceholder: 'Pegue o escriba la tablatura aquí (ej: e|---0---1---0---|)...',
    tagsPlaceholder: 'ej. Rock, Pop, Años 80',
    durationPlaceholder: 'ej. 03:45',
    tagsLabel: 'ETIQUETAS ( , )',
    durationLabel: 'DURACIÓN (MM:SS)',
    lyricsLabel: 'Letra',
    chordsLabel: 'Acordes',
    tabsLabel: 'Tablatura',
    lyricsFormLabel: 'Letra',
    chordsFormLabel: 'Acordes',
    tabsFormLabel: 'Tablatura',
    defaultViewLabel: 'VISTA PREDETERMINADA',
    scrollSpeedLabel: 'VELOCIDAD DE SCROLL',
    defaultScrollSpeed: 'VELOCIDAD DE DESPLAZAMIENTO PREDETERMINADA (AUTOSCROLL)',
    supportLinks: 'ENLACES DE APOYO',
    songDetails: 'DETALLES DE LA CANCIÓN',
    cifras: 'Acordes',
    addLink: 'Añadir Nuevo Enlace',
    removeLink: 'Eliminar Enlace',
    invalidDurationTitle: 'Duración Inválida',
    invalidDurationMsg: 'Por favor, ingrese la duración en formato MM:SS (ej: 03:45) o deje el campo vacío.',
    editSongContent: 'EDITAR CONTENIDO DE LA CANCIÓN',
    disabledLabel: 'Desactivado',
    saveSong: 'GUARDAR CANCIÓN',
    alertSongName: 'Por favor, introduzca el nombre de la canción.',
    alertOriginalBand: 'Por favor, introduzca la banda original.',
    deleteSongConfirmTitle: 'Eliminar Canción',
    deleteSongConfirmMsg: '¿Está seguro de que desea eliminar esta canción de la base de datos global?',
    deleteSongError: 'No se pudo eliminar la canción.',
    songAlreadyExists: 'La canción "{name}" ya existe en la base de datos y no fue duplicada.',
    songsBadge: 'canc.',
    tagAll: 'Todas las Etiquetas',
    filterByTag: 'Filtrar por Etiqueta',
    filterByStatus: 'Filtrar por Estado',
    allStatuses: 'Todos',
    songInfoBpm: 'BPM',
    songInfoCapo: 'Capo',
    songInfoKey: 'Tono',

    songSingular: 'canción',
    songPlural: 'canciones',

    // Gestión de Setlists
    addSetlist: '+ Setlist',
    newSetlist: 'NUEVO SETLIST',
    editSetlist: 'EDITAR SETLIST',
    presentationType: 'TIPO DE EVENTO',
    show: 'Show',
    rehearsal: 'Ensayo',
    repertoire: 'Repertorio',
    responsibleBand: 'BANDA RESPONSABLE *',
    registerBandFirst: '¡Registre al menos una banda antes de crear el setlist!',
    setlistNameLabel: 'NOMBRE DEL SETLIST *',
    setlistNamePlaceholder: 'Nombre del Evento',
    addSongBtn: '+ Canción',
    addPauseBtn: '+ Pausa',
    addNoteBtn: '+ Nota',
    datePlaceholder: 'AAAA-MM-DD',
    localPlaceholder: 'ej. Bar de Joe, Estudio X...',
    cachetPlaceholder: 'ej. 500',
    dateLabel: 'FECHA *',
    localLabel: 'LUGAR',
    cachêLabel: 'Pago',
    notesLabel: 'NOTAS DEL EVENTO',
    selectAll: 'Seleccionar Todas',
    deselectAll: 'Desmarcar Todas',
    selectedSongsCount: 'seleccionada(s)',
    noSongsCollection: 'Ninguna canción encontrada en la colección.',
    saveRepertoire: 'Guardar Repertorio',
    linkCollectionSongs: 'CANCIONES DE LA COLECCIÓN',
    searchCollectionSong: 'Buscar en la colección...',
    addSelectedCount: 'AÑADIR SELECCIONADAS',
    dragToReorderTip: 'Arrastra por ☰ para reordenar',
    swipeToDeleteTip: 'Desliza a la izquierda para eliminar',
    pauseItem: 'PAUSA',
    editPauseTitle: 'EDITAR PAUSA',
    editNoteTitle: 'EDITAR NOTA',
    typeNotePrompt: 'Escriba su nota o aviso...',
    durationExamplePlaceholder: 'ej. 5 min, 10 min',
    foundPlural: 'encontrada(s)',
    copySetlistBtn: 'Copiar Setlist',
    setlistCopiedMsg: '¡Setlist copiado con éxito!',
    setlistCopyError: 'No se pudo duplicar el setlist.',
    availableSongs: 'CANCIONES DISPONIBLES',
    songsLabel: 'CANCIONES DISPONIBLES',
    reorderBtn: 'REORDENAR',
    reorderTitle: 'REORDENAR SETLIST',
    reorderHelp: 'Arrastre por el icono ☰ para reordenar. Toque X para eliminar.',
    reorderTip: 'Toca una canción para seleccionarla, luego toca otra posición para moverla instantáneamente.',
    reorderTipDrag: 'Arrastre las canciones sosteniendo el icono (☰) a la derecha para ordenar el setlist suavemente.',
    selectedSongsLabel: 'CANCIONES SELECCIONADAS (ARRASTRE PARA ORDENAR)',
    createSetlist: 'CREAR SETLIST',
    noteItem: 'NOTA',
    notePlaceholder: 'Escriba notas del evento o de la presentación...',
    alertSetlistName: 'Por favor, introduzca el nombre del setlist.',
    alertSelectBand: 'Por favor, seleccione una banda asociada.',
    alertSetlistDate: 'Por favor, introduzca la fecha del setlist.',
    alertSelectSong: 'Por favor, seleccione al menos una canción para el setlist.',
    alertSelectSongOrPauseFirst: 'Seleccione una canción o pausa primero.',
    deleteSetlistConfirmTitle: 'Eliminar Setlist',
    deleteSetlistConfirmMsg: '¿Está seguro de que desea eliminar este setlist?',
    deleteSetlistError: 'No se pudo eliminar el setlist.',
    addToSetlist: 'AÑADIR AL SETLIST',
    noSongsInSetlist: 'Ninguna canción seleccionada para este setlist aún.',
    reorderDoneBtn: 'CONCLUIDO',

    // Selector Múltiple de Canciones
    addSongsBtn: 'AGREGAR CANCIONES',
    selectSongsModalTitle: 'SELECCIONAR CANCIONES',
    selectAll: 'Marcar Todas',
    deselectAll: 'Desmarcar Todas',
    addSelectedCount: 'AGREGAR SELECCIONADAS',
    selectedCount: 'seleccionada(s)',
    noSongsFoundInPicker: 'Ninguna canción encontrada.',

    // Tarjeta de Setlist y Detalles
    dateText: 'Fecha',
    localText: 'Lugar',
    cachêText: 'Pago',
    cacheText: 'Pago',
    notesText: 'Notas',
    typeText: 'Tipo',
    songsCount: 'Canciones',
    songsTitle: 'CANCIONES DEL SETLIST',
    estimatedTime: 'Tiempo Estimado',
    venue: 'Lugar',
    noSongsInCard: 'Ningún setlist encontrado para los filtros activos.',
    noSongsInDetail: 'Ninguna canción asociada a este setlist.',
    detailTitle: 'DETALLES DEL SETLIST',
    startStage: 'Escenario',
    startStageBtn: 'MODO ESCENARIO',
    setlistTabRepertoire: 'REPERTORIO',
    setlistTabDetails: 'DATOS DEL EVENTO',
    editNoteTitle: 'EDITAR NOTA',
    editPauseTitle: 'EDITAR PAUSA',
    duplicateSetlist: 'Duplicar Setlist',
    createCopy: 'Crear Copia',
    showsAndCaches: 'Shows y Pagos de Eventos',
    noCachetDefined: 'Sin Pago registrado',
    nextEventHero: 'PRÓXIMO EVENTO',
    membersBadge: 'integrantes',
    tapToEditSongTip: 'Toque en la canción para editar acordes/letra',
    dragToReorderTip: 'Arrastre por el icono ☰ para reordenar',
    swipeToDeleteTip: 'Deslice a la izquierda para eliminar',
    rehearsalNotesPlaceholder: 'Notas del ensayo (opcional)',

    // Modo Escenario (Performance)
    pause: 'PAUSA',
    pauseTitle: 'PAUSA / INTERVALO',
    note: 'NOTA',
    noteTitle: 'NOTA / ANOTACIÓN',
    rehearsalReport: 'SETLIST COMPLETO',
    noLyrics: 'Ninguna letra registrada para esta canción.',
    noChords: 'Ningún acorde registrado para esta canción.',
    noTabs: 'Ninguna tablatura registrada para esta canción.',
    noContentRegistered: 'Ningún contenido registrado para esta canción.',
    timerCountdown: 'Cuenta Regresiva',
    timerPaused: 'Pausado',
    timerFinished: '¡PAUSA FINALIZADA!',
    timerNoLimit: 'SIN LÍMITE DE TIEMPO',
    pauseTimer: 'PAUSAR TEMPORIZADOR',
    startTimer: 'INICIAR TEMPORIZADOR',
    resetTimer: 'REINICIAR',
    closeList: 'CERRAR LISTA',

    // Modal de Importación
    importBtnText: 'Importar',
    importTitle: 'IMPORTAR DATOS',
    importTitleSetlist: 'IMPORTAR SETLIST',
    importTitleSong: 'IMPORTAR CANCIÓN',
    importDescSetlist: 'Seleccione el archivo del setlist (.json) o pegue el código en el editor abajo para importar.',
    importDescSong: 'Seleccione el archivo de la canción (.json) o pegue el código en el editor abajo para importar.',
    fileTypeLabelSong: 'canción',
    fileTypeLabelSetlist: 'setlist',
    fileTypeLabelBackup: 'respaldo',
    pasteJsonLabel: 'PEGAR CÓDIGO JSON AQUÍ',
    importBtn: 'IMPORTAR DATOS',
    importNow: 'IMPORTAR AHORA',
    selectFileLabel: 'SELECCIONAR ARCHIVO JSON',
    orPasteCode: 'O PEGUE EL CÓDIGO DE TEXTO',
    importSuccessSong: '¡Canción importada con éxito!',
    importSuccessSetlist: '¡Setlist importado con éxito!',
    importErrorTitle: 'Error al Importar',
    importErrorMsg: 'No se pudieron importar los datos. Verifique el formato JSON.',
    invalidJsonMsg: 'El código pegado no es un JSON válido.',
    fileLoadedAlert: '¡Archivo cargado! Haga clic en IMPORTAR AHORA para finalizar.',
    fileReadError: 'No se pudo leer el archivo seleccionado.',

    // Tema y Apariencia
    themeAppearance: 'TEMA Y APARIENCIA',
    themeMode: 'MODO DE TEMA',
    dark: 'Oscuro',
    light: 'Claro',
    primaryColor: 'COLOR PRIMARIO',
    secondaryColor: 'COLOR SECUNDARIO',
    appLanguage: 'IDIOMA DE LA APP',

    // Copia de Seguridad y Restauración
    backupSectionTitle: 'COPIA DE SEGURIDAD Y RESTAURACIÓN',
    backupSubtitle: 'Exporte o importe toda la base de datos de la app (bandas, canciones y setlists) con total seguridad.',
    backupExportBtn: 'RESPALDO TOTAL (EXPORTAR)',
    backupImportBtn: 'RESTAURAR RESPALDO (IMPORTAR)',
    backupExportSuccess: '¡Copia de seguridad exportada con éxito! Archivo listo para compartir o guardar.',
    backupExportError: 'No se pudo generar el archivo de copia de seguridad.',
    backupImportConfirmTitle: 'Restaurar Respaldo',
    backupImportConfirmMsg: 'Elija cómo desea restaurar el respaldo:\n\n• REEMPLAZAR: Sobrescribe completamente los datos actuales con la copia de seguridad.\n• FUSIONAR: Combina los datos del respaldo sin eliminar los existentes.',
    backupImportReplace: 'REEMPLAZAR (Sobrescribir)',
    backupImportMerge: 'FUSIONAR (Combinar)',
    backupImportSuccess: '¡Copia de seguridad restaurada con éxito! Base de datos actualizada.',
    backupImportError: 'No se pudo restaurar la copia de seguridad. Verifique el formato del archivo.',
    backupTipsTitle: 'Consejos de Seguridad y Respaldo',
    protectDataLabel: 'Cómo proteger los datos de su repertorio:',
    tip2: '• Realice copias de seguridad manuales: Guarde sus setlists más importantes generando códigos de exportación o archivos JSON con el botón compartir y guardándolos en WhatsApp o notas.',
    tip3: '• Restaurar datos: Si necesita reinstalar la aplicación o cambiar de dispositivo, use la opción Importar en la pestaña correspondiente y pegue el código o seleccione el archivo para recuperar todo al instante.',
    backupAllBtn: 'RESPALDO TOTAL',
    restoreBackupBtn: 'RESTAURAR RESPALDO',
    restoreBackupTitle: 'RESTAURAR RESPALDO',
    restoreBackupDesc: 'Seleccione el archivo de respaldo (.json) o pegue el código en el editor abajo para restaurar todos los datos.',
    backupCreatedAlert: '¡Respaldo creado con éxito!',
    codeCopied: '¡y copiado al portapapeles!',
    backupAllTitle: 'Respaldo Total de Datos',

    // Acerca de la Aplicación
    loadingDatabase: 'Cargando base de datos...',
    aboutTitle: 'ACERCA DE SETLIST APP',
    aboutHeader: 'ACERCA DE',
    aboutTheApp: 'La Aplicación',
    aboutAppDesc: 'Setlist Band Manager es una herramienta profesional diseñada para ayudar a músicos, bandas y productores a organizar su repertorio y setlists de manera impecable.',
    aboutFeatures: 'Funcionalidades Principales',
    aboutDev: 'DESARROLLADO POR:',
    version: 'Versión',
    versionText: 'Versión',
    developer: 'Desarrollador',
    developedBy: 'Desarrollado con dedicación para músicos, bandas y artistas.',
    featuresTitle: 'FUNCIONALIDADES',
    feature1: 'Gestión completa de Setlists, Repertorios y Ensayos.',
    feature2: 'Modo Escenario con desplazamiento automático y acordes.',
    feature3: 'Soporte multibandas con repertorios personalizados.',
    feature4: 'Exportación a Word (.doc), JSON y Respaldo Total.',
    feature5: 'Copia de seguridad y restauración completa para total seguridad.',
    feature6: 'Soporte para múltiples temas visuales y modo oscuro.',
    aboutFeature1Title: 'Gestión Multibandas',
    aboutFeature1Desc: 'Registre sus bandas con foto/logo y gestione los setlists y repertorios de cada proyecto.',
    aboutFeature2Title: 'Repertorio Estructurado',
    aboutFeature2Desc: 'Guarde letras, acordes, tablaturas, duración y enlaces de apoyo organizadamente.',
    aboutFeature3Title: 'Modo Escenario',
    aboutFeature3Desc: 'Vea acordes y letras en pantalla completa con desplazamiento automático y marquesina dinámica.',
    aboutFeature4Title: 'Ensayos Inteligentes',
    aboutFeature4Desc: 'Evalúe el rendimiento de las canciones en el ensayo con colores (verde/amarillo/rojo), cree observaciones y guarde todo.',
    aboutFeature5Title: 'Compartir, Exportar y Respaldo',
    aboutFeature5Desc: 'Exporte setlists a Word (.doc), comparta en JSON y realice copia de seguridad y restauración total.',
    aboutFeature6Title: 'Soporte Multilingüe y Temas',
    aboutFeature6Desc: 'Cambie entre Portugués, Inglés y Español y personalice el diseño con colores premium.',
    aboutFeature7Title: 'Fijados y Favoritos',
    aboutFeature7Desc: 'Marque setlists y canciones con una estrella para mantenerlos fijados al principio automáticamente.',
    aboutFeature8Title: 'Múltiples Etiquetas & Filtros',
    aboutFeature8Desc: 'Registre canciones con múltiples etiquetas por coma y filtre combinando hasta 3 etiquetas simultáneas.',
    aboutFeature9Title: 'Reordenación por Arrastre',
    aboutFeature9Desc: 'Organice el orden de las canciones en el setlist arrastrando de forma suave y rápida con física de muelle y vibración.',
    aboutFeature10Title: 'Líneas de Anotación y Notas',
    aboutFeature10Desc: 'Agregue avisos, observaciones o saltos de sección directamente en el setlist como pantallas de destaque en el Modo Escenario.',
    tutorialGuide: 'TUTORIAL PRÁCTICO',
    tapForTutorial: 'TOCA PARA LA GUÍA',
    stepByStep: 'CÓMO USAR PASO A PASO:',
    proTip: 'CONSEJO DE ORO:',
    understood: 'ENTENDIDO',

    // Sincronización Web y Compartir QR
    webEditorTitle: 'WEB EDITOR',
    webSyncSubtitle: 'Conecte a su computadora (PC) u otro celular mediante código QR o PIN',
    webSyncDesc: 'Transfiera todo su repertorio, letras, acordes y setlists entre la aplicación móvil, la PC u otro celular con solo 1 escaneo de cámara o código PIN de 6 dígitos.',
    openSyncQrBtn: 'ABRIR SINCRONIZADOR QR CODE',
    syncModalTitle: 'Sincronizar & Compartir',
    syncModalSubtitle: 'Web Editor (PC) u Otro Celular',
    connectedSuccess: '¡Conectado con Éxito!',
    chooseAction: 'Elija la acción deseada:',
    sendToPcTitle: 'ENVIAR A PC',
    sendToPcDesc: 'Envía todas las canciones de este celular a la computadora',
    pullFromPcTitle: 'OBTENER DE PC / CELULAR',
    pullFromPcDesc: 'Descarga el repertorio compartido a este celular',
    scanAnotherCode: 'Escanear otro código',
    tabScanQr: 'Leer QR',
    tabGenerateQr: 'Generar QR',
    tabPin: 'PIN',
    cameraPermRequired: 'Acceso a Cámara Necesario',
    cameraPermDesc: 'Para leer el código QR en el monitor de la PC o en otro celular, necesitamos permiso de la cámara.',
    allowCameraBtn: 'Permitir Cámara',
    pointCameraInstruction: 'Apunte al código QR de la PC o del celular',
    preparingQrCode: 'Preparando repertorio y generando código QR...',
    pinCodeLabel: 'CÓDIGO PIN:',
    qrInstruction: 'En el otro dispositivo, abra la app, vaya a "Leer QR" y apunte la cámara hacia esta pantalla.',
    generateNewCode: 'Generar Nuevo Código',
    shareWithNearbyPhone: 'Compartir con Celular Cercano',
    shareWithNearbyPhoneDesc: 'Genere un código QR en pantalla para enviar todas sus canciones y setlists directamente al celular de otro integrante de la banda.',
    generateQrNowBtn: 'Generar Código QR Ahora',
    transferSuccessTitle: '¡Éxito! 🎉',
    transferSuccessMsg: '¡Su repertorio fue transferido con éxito al otro celular!',
    enterPinTitle: 'Ingrese el PIN de 6 Dígitos',
    enterPinDesc: 'Código mostrado en la pantalla de la PC o del otro celular:',
    connectByPinBtn: 'Conectar e Importar',
    pullingData: 'Descargando repertorio...',
    savingSongsLocally: 'Guardando canciones en el celular...',
    repertoireReceivedTitle: '¡Repertorio Recibido! 🎉',
    repertoireReceivedMsg: '¡Todas las canciones y setlists compartidos fueron importados y guardados en su dispositivo!',
    repertoireReceivedPinMsg: '¡Canciones y setlists importados con éxito vía PIN!',
    invalidPinTitle: 'PIN Inválido',
    invalidPinMsg: 'Ingrese el código numérico de 6 dígitos.',
    connectingPin: 'Conectando al código PIN...',
    sessionNotFoundTitle: 'Sesión No Encontrada',
    sessionNotFoundMsg: 'Código PIN incorrecto o expirado.',
    collectingRepertoire: 'Recolectando repertorio y setlists...',
    transmittingToPc: 'Transmitiendo datos a la pantalla de la PC...',
    transmittedSuccessTitle: '¡Éxito! 🎉',
    transmittedSuccessMsg: '¡Todos los datos fueron transmitidos con éxito al Web Editor en la PC!',
    transmissionErrorTitle: 'Error en la Transmisión',
    transmissionErrorMsg: 'No se pudieron enviar los datos.',
    connectionErrorTitle: 'Error de Conexión',
    connectionErrorMsg: 'Verifique su conexión a internet e inténtelo de nuevo.',
    fetchingWebData: 'Buscando datos del Web Editor...',
    updatingDatabaseMsg: 'Actualizando base de datos en el celular...',
    syncCompletedTitle: '¡Sincronización Completada! 🚀',
    syncCompletedMsg: '¡Todas las canciones y setlists editados en la PC fueron importados a su celular!',
    awaitingDataTitle: 'Esperando Datos',
    awaitingDataMsg: 'Ningún dato ha sido enviado desde la PC aún. En el Web Editor, haga clic en "Enviar al Celular".',
    invalidQrTitle: 'Código QR Inválido',
    invalidQrMsg: 'El código escaneado no pertenece a Setlist Band Manager.',
    processQrError: 'No se pudo procesar el código QR.',
    sessionGenerateError: 'No se pudo generar la sesión de compartir.',
    connectedToPin: 'Conectado al PIN',
    connectedToSession: 'Conectado a la Sesión',

    // Filtros y Tipos de Evento
    filterPrefix: 'FILTRO:',
    filterAll: 'TODAS',
    filterShows: 'SHOWS',
    filterRehearsals: 'ENSAYOS',
    filterRepertoire: 'REPERTORIO',
    allPlural: 'TODAS',
    ensaio: 'Ensayo',
    repertório: 'Repertorio',
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState('en');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function loadLang() {
      try {
        const savedLang = await settingsService.getSetting('appLanguage', 'en');
        setLanguageState(savedLang);
      } catch (error) {
        console.error('Error loading language setting:', error);
      } finally {
        setLoading(false);
      }
    }
    loadLang();
  }, []);

  const setLanguage = async (lang) => {
    setLanguageState(lang);
    await settingsService.setSetting('appLanguage', lang);
  };

  const t = (key) => {
    const langDict = translations[language] || translations.en || translations.pt;
    return langDict[key] || (translations.en && translations.en[key]) || translations.pt[key] || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
        loading
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
