import React, { createContext, useContext, useState, useEffect } from 'react';
import { settingsService } from '../services/settingsService';

const translations = {
  pt: {
    // Navegação e Abas
    home: 'Início',
    songs: 'Músicas',
    setlists: 'Setlists',
    about: 'Sobre',

    // Ações Gerais e Modais
    confirm: 'Confirmar',
    cancel: 'Cancelar',
    save: 'SALVAR',
    close: 'Fechar',
    closeBtn: 'FECHAR',
    edit: 'Editar',
    delete: 'Excluir',
    copy: 'Duplicar',
    share: 'Compartilhar',
    exportWord: 'Exportar Word',
    exportPdf: 'PDF',
    generatingPdf: 'Gerando PDF...',
    pdfSuccess: 'PDF criado com sucesso!',
    pdfError: 'Não foi possível gerar o PDF.',
    exportDocSuccess: 'Documento exportado com sucesso!',
    shareTitle: 'Compartilhar',
    sharePrompt: 'Escolha o formato:',
    shareAsFile: 'Arquivo Físico (.json)',
    shareAsFileDesc: 'Ideal para enviar para outros usuários do app importarem.',
    shareAsText: 'Texto Formatado',
    shareAsTextDesc: 'Ideal para enviar via WhatsApp, Telegram, etc.',
    shareSuccess: 'Compartilhado com sucesso!',
    search: 'Buscar...',
    searchPlaceholder: 'Buscar...',
    searchPlaceholderDesc: 'Buscar por título, artista ou estilo...',
    emptyState: 'Nenhum registro encontrado.',
    attention: 'Atenção',
    success: 'Sucesso',
    info: 'Informação',
    optionsBtn: 'Opções',
    optionsTitle: 'Opções',
    done: 'CONCLUÍDO',

    // Tela Inicial (Home)
    myBands: 'Minhas Bandas',
    quickStats: 'ESTATÍSTICAS RÁPIDAS',
    totalSongs: 'Total de Músicas',
    totalSetlists: 'Total de Setlists',
    noBands: 'Nenhuma banda cadastrada ainda. Clique em "+ Banda" no topo para criar!',
    noSongs: 'Nenhuma música encontrada. Clique em "+ Música" no topo para cadastrar!',
    upcomingEvents: 'PRÓXIMOS EVENTOS',
    myBandsCarouselSubtitle: 'Minhas Bandas (Toque longo para editar/excluir)',
    allBands: 'Todas as Bandas',
    showingAllBands: 'Exibindo todas as bandas',
    showingBandSetlist: 'Exibindo setlists de',
    showingBandSongs: 'Exibindo músicas de',
    viewAllBands: 'Ver todas as bandas',

    // Gestão de Bandas
    addBand: '+ Banda',
    newBand: 'NOVA BANDA',
    editBand: 'EDITAR BANDA',
    bandNameLabel: 'NOME DA BANDA *',
    coverImageLabel: 'FOTO DE CAPA (OPCIONAL)',
    imageSelected: 'Imagem Selecionada',
    chooseImage: 'Escolher Imagem da Galeria',
    removeImage: 'Remover Imagem',
    saveChanges: 'SALVAR ALTERAÇÕES',
    createBand: 'CRIAR NOVA BANDA',
    deleteBandConfirmTitle: 'Excluir Banda',
    deleteBandConfirmMsg: 'Tem certeza que deseja excluir a banda "{name}"? Setlists vinculados a esta banda terão o campo de banda limpo.',
    deleteBandError: 'Não foi possível excluir a banda.',
    noBand: 'Sem Banda',

    // Gestão de Músicas
    addSong: '+ Música',
    newSong: 'NOVA MÚSICA',
    editSong: 'EDITAR MÚSICA',
    songNameLabel: 'NOME DA MÚSICA *',
    originalBandLabel: 'BANDA ORIGINAL *',
    tagsLabel: 'TAGS ( , )',
    durationLabel: 'DURAÇÃO (MM:SS)',
    lyricsLabel: 'Letra',
    chordsLabel: 'Cifra',
    tabsLabel: 'Tablatura',
    lyricsFormLabel: 'Letra',
    chordsFormLabel: 'Cifra',
    tabsFormLabel: 'Tablatura',
    defaultViewLabel: 'VISUALIZAÇÃO PADRÃO',
    scrollSpeedLabel: 'VELOCIDADE DO SCROLL',
    defaultScrollSpeed: 'VELOCIDADE DE ROLAGEM PADRÃO (AUTOSCROLL)',
    supportLinks: 'LINKS DE APOIO',
    addLink: 'Adicionar Novo Link',
    removeLink: 'Remover Link',
    invalidDurationTitle: 'Duração Inválida',
    invalidDurationMsg: 'Por favor, insira a duração no formato MM:SS (ex: 03:45) ou deixe o campo vazio.',
    editSongContent: 'EDITAR CONTEÚDO DA MÚSICA',
    disabledLabel: 'Desativada',
    saveSong: 'SALVAR MÚSICA',
    alertSongName: 'Informe o nome da música.',
    alertOriginalBand: 'Informe a banda original.',
    deleteSongConfirmTitle: 'Excluir Música',
    deleteSongConfirmMsg: 'Tem certeza de que deseja excluir esta música do banco de dados global?',
    deleteSongError: 'Não foi possível excluir a música.',
    songAlreadyExists: 'A música "{name}" já existe no banco de dados e não foi duplicada.',
    songsBadge: 'mús.',
    tagAll: 'Todas as Tags',
    filterByTag: 'Filtrar por Tag',
    filterByStatus: 'Filtrar por Status',
    allStatuses: 'Todos',
    songInfoBpm: 'BPM',
    songInfoCapo: 'Capo',
    songInfoKey: 'Tom',

    // Gestão de Setlists
    addSetlist: '+ Setlist',
    newSetlist: 'NOVO SETLIST',
    editSetlist: 'EDITAR SETLIST',
    presentationType: 'TIPO DE EVENTO',
    show: 'Show',
    rehearsal: 'Ensaio',
    repertoire: 'Repertório',
    responsibleBand: 'BANDA RESPONSÁVEL *',
    registerBandFirst: 'Cadastre ao menos uma banda antes de criar o setlist.',
    setlistNameLabel: 'NOME DO SETLIST *',
    dateLabel: 'DATA *',
    localLabel: 'LOCAL',
    cachêLabel: 'CACHÊ (R$)',
    notesLabel: 'OBSERVAÇÕES DO EVENTO',
    availableSongs: 'MÚSICAS DISPONÍVEIS',
    songsLabel: 'MÚSICAS DISPONÍVEIS',
    reorderBtn: 'REORDENAR',
    reorderTitle: 'REORDENAR ROTEIRO',
    reorderHelp: 'Arraste pelo ícone ☰ para reordenar. Toque no X para remover.',
    reorderTip: 'Toque em uma música para selecioná-la, depois toque em outra posição para movê-la instantaneamente.',
    reorderTipDrag: 'Arraste as músicas segurando no ícone (☰) à direita para ordenar o roteiro suavemente.',
    selectedSongsLabel: 'MÚSICAS SELECIONADAS (ARRASTE PARA ORDENAR)',
    createSetlist: 'CRIAR SETLIST',
    noteItem: 'ANOTAÇÃO',
    notePlaceholder: 'Digite observações do evento ou da apresentação...',
    alertSetlistName: 'Informe o nome do setlist.',
    alertSelectBand: 'Selecione uma banda associada.',
    alertSetlistDate: 'Informe a data do setlist.',
    alertSelectSong: 'Selecione pelo menos uma música para o setlist.',
    alertSelectSongOrPauseFirst: 'Selecione uma música ou pausa primeiro.',
    deleteSetlistConfirmTitle: 'Excluir Setlist',
    deleteSetlistConfirmMsg: 'Tem certeza de que deseja excluir este setlist?',
    deleteSetlistError: 'Não foi possível excluir o setlist.',
    addToSetlist: 'ADICIONAR AO ROTEIRO',
    noSongsInSetlist: 'Nenhuma música selecionada para este setlist ainda.',
    reorderDoneBtn: 'CONCLUÍDO',

    // Seletor Múltiplo de Músicas
    addSongsBtn: 'ADICIONAR MÚSICAS',
    selectSongsModalTitle: 'SELECIONAR MÚSICAS',
    selectAll: 'Marcar Todas',
    deselectAll: 'Desmarcar Todas',
    addSelectedCount: 'ADICIONAR SELECIONADAS',
    selectedCount: 'selecionada(s)',
    noSongsFoundInPicker: 'Nenhuma música encontrada.',

    // Card de Setlist e Detalhes
    dateText: 'Data',
    localText: 'Local',
    cachêText: 'Cachê',
    cacheText: 'Cachê',
    notesText: 'Observações',
    typeText: 'Tipo',
    songsCount: 'Músicas',
    songsTitle: 'MÚSICAS DO ROTEIRO',
    estimatedTime: 'Tempo Estimado',
    venue: 'Local',
    noSongsInCard: 'Nenhum setlist encontrado para os filtros ativos.',
    noSongsInDetail: 'Nenhuma música associada a este setlist.',
    detailTitle: 'DETALHES DO SETLIST',
    startStage: 'Palco',
    startStageBtn: 'MODO PALCO',
    setlistTabRepertoire: 'ROTEIRO',
    setlistTabDetails: 'DADOS DO EVENTO',
    editNoteTitle: 'EDITAR ANOTAÇÃO',
    editPauseTitle: 'EDITAR PAUSA',
    tapToEditSongTip: 'Toque na música para editar cifra/letra',
    dragToReorderTip: 'Arraste pelo ícone ☰ para reordenar',
    swipeToDeleteTip: 'Deslize para a esquerda para excluir',
    rehearsalNotesPlaceholder: 'Observações do ensaio (opcional)',

    // Modo Palco (Performance)
    pause: 'PAUSA',
    pauseTitle: 'PAUSA / INTERVALO',
    rehearsalReport: 'ROTEIRO COMPLETO',
    noLyrics: 'Nenhuma letra cadastrada para esta música.',
    noChords: 'Nenhuma cifra cadastrada para esta música.',
    noTabs: 'Nenhuma tablatura cadastrada para esta música.',
    noContentRegistered: 'Nenhum conteúdo cadastrado para esta música.',
    timerCountdown: 'Contagem Regressiva',
    timerPaused: 'Pausado',
    timerFinished: 'PAUSA FINALIZADA!',
    timerNoLimit: 'SEM LIMITE DE TEMPO',
    pauseTimer: 'PAUSAR CONTADOR',
    startTimer: 'INICIAR CONTADOR',
    resetTimer: 'RESETAR',
    closeList: 'FECHAR LISTA',

    // Modal de Importação
    importBtnText: 'Importar',
    importTitle: 'IMPORTAR DADOS',
    importTitleSetlist: 'IMPORTAR SETLIST',
    importTitleSong: 'IMPORTAR MÚSICA',
    importDescSetlist: 'Selecione o arquivo físico de setlist (.json) ou cole o código no editor abaixo para importar.',
    importDescSong: 'Selecione o arquivo físico de música (.json) ou cole o código no editor abaixo para importar.',
    fileTypeLabelSong: 'de música',
    fileTypeLabelSetlist: 'de setlist',
    fileTypeLabelBackup: 'de backup',
    pasteJsonLabel: 'COLE O CÓDIGO JSON AQUI',
    importBtn: 'IMPORTAR DADOS',
    importNow: 'IMPORTAR AGORA',
    selectFileLabel: 'SELECIONAR ARQUIVO JSON',
    orPasteCode: 'OU COLE O CÓDIGO TEXTO',
    importSuccessSong: 'Música importada com sucesso!',
    importSuccessSetlist: 'Setlist importado com sucesso!',
    importErrorTitle: 'Erro ao Importar',
    importErrorMsg: 'Não foi possível importar os dados. Verifique a formatação do JSON.',
    invalidJsonMsg: 'O código colado não é um JSON válido.',
    fileLoadedAlert: 'Arquivo carregado! Clique em IMPORTAR AGORA para finalizar.',
    fileReadError: 'Não foi possível ler o arquivo selecionado.',

    // Tema e Aparência
    themeAppearance: 'TEMA E APARÊNCIA',
    themeMode: 'MODO DO TEMA',
    dark: 'Escuro',
    light: 'Claro',
    primaryColor: 'COR PRIMÁRIA',
    secondaryColor: 'COR SECUNDÁRIA',
    appLanguage: 'IDIOMA DO APLICATIVO',

    // Backup e Restauração
    backupSectionTitle: 'BACKUP E RESTAURAÇÃO',
    backupSubtitle: 'Exporte ou importe todo o banco de dados do app (bandas, músicas e setlists) com total segurança.',
    backupExportBtn: 'BACKUP TOTAL (EXPORTAR)',
    backupImportBtn: 'RESTAURAR BACKUP (IMPORTAR)',
    backupExportSuccess: 'Backup exportado com sucesso! Arquivo pronto para compartilhar ou salvar.',
    backupExportError: 'Não foi possível gerar o arquivo de backup.',
    backupImportConfirmTitle: 'Restaurar Backup',
    backupImportConfirmMsg: 'Escolha como deseja restaurar o backup:\n\n• SUBSTITUIR: Sobrescreve completamente os dados atuais pelo backup.\n• MESCLAR: Combina os dados do backup sem apagar os existentes.',
    backupImportReplace: 'SUBSTITUIR (Sobrescrever)',
    backupImportMerge: 'MESCLAR (Combinar)',
    backupImportSuccess: 'Backup restaurado com sucesso! Banco de dados atualizado.',
    backupImportError: 'Não foi possível restaurar o backup. Verifique o formato do arquivo.',
    backupTipsTitle: 'Dicas de Backup e Segurança',
    protectDataLabel: 'Como proteger seus dados de repertório:',
    tip1: '• Não desinstale para atualizar: Para instalar novas atualizações, basta abrir o APK atualizado e instalá-lo por cima do antigo. Caso você desinstale o app completamente, o banco de dados local será deletado do celular pelo sistema operacional.',
    tip2: '• Faça backups manuais: Salve seus setlists mais importantes gerando os códigos de exportação com o botão de compartilhamento e guardando-os no WhatsApp ou bloco de notas.',
    tip3: '• Restaurar dados: Se precisar reinstalar o aplicativo ou trocar de aparelho, utilize a opção Importar na aba correspondente e cole o código ou selecione o arquivo para recuperar tudo instantaneamente.',
    backupAllBtn: 'BACKUP TOTAL',
    restoreBackupBtn: 'RESTAURAR BACKUP',
    restoreBackupTitle: 'RESTAURAR BACKUP',
    restoreBackupDesc: 'Selecione o arquivo de backup (.json) ou cole o código no editor abaixo para restaurar todos os dados.',
    backupCreatedAlert: 'Backup criado com sucesso!',
    codeCopied: 'e copiado para a área de transferência!',
    backupAllTitle: 'Backup Total de Dados',

    // Sobre o Aplicativo
    loadingDatabase: 'Carregando banco...',
    aboutTitle: 'SOBRE O SETLIST APP',
    aboutHeader: 'SOBRE',
    aboutTheApp: 'O Aplicativo',
    aboutAppDesc: 'O Setlist Band Manager é uma ferramenta profissional projetada para auxiliar músicos, bandas e produtores a organizarem seu repertório e seus roteiros de shows de forma impecável.',
    aboutFeatures: 'Funcionalidades Principais',
    aboutDev: 'DESENVOLVIDO POR:',
    version: 'Versão',
    versionText: 'Versão',
    developer: 'Desenvolvedor',
    developedBy: 'Desenvolvido com dedicação para músicos, bandas e artistas.',
    featuresTitle: 'FUNCIONALIDADES',
    feature1: 'Gestão completa de Setlists, Repertórios e Ensaios.',
    feature2: 'Modo Palco com rolagem automática e visualização de cifras.',
    feature3: 'Suporte multibandas com repertórios personalizados.',
    feature4: 'Exportação para Word (.doc), JSON e Backup Total.',
    feature5: 'Backup e Restauração completa para total segurança.',
    feature6: 'Suporte a múltiplos temas visuais e modo escuro.',
    aboutFeature1Title: 'Gestão Multibandas',
    aboutFeature1Desc: 'Cadastre suas bandas com foto/logo e gerencie os roteiros e repertórios de cada projeto.',
    aboutFeature2Title: 'Repertório Estruturado',
    aboutFeature2Desc: 'Guarde letras, cifras, tablaturas, duração e links de apoio de forma organizada.',
    aboutFeature3Title: 'Modo Palco',
    aboutFeature3Desc: 'Visualize cifras e letras em tela cheia com rolagem automática e letreiro dinâmico.',
    aboutFeature4Title: 'Ensaios Inteligentes',
    aboutFeature4Desc: 'Avalie o desempenho das músicas no ensaio com cores (verde/amarelo/vermelho), crie observações e salve tudo.',
    aboutFeature5Title: 'Compartilhamento, Exportação e Backup',
    aboutFeature5Desc: 'Exporte setlists em Word (.doc), compartilhe em JSON e faça backup e restauração total do banco de dados.',
    aboutFeature6Title: 'Multilíngue e Personalização',
    aboutFeature6Desc: 'Alterne o idioma entre Português, Inglês e Espanhol e escolha cores primárias e secundárias premium.',
    aboutFeature7Title: 'Fixados e Favoritos',
    aboutFeature7Desc: 'Marque setlists e músicas com estrela para mantê-los fixados no topo automaticamente.',
    aboutFeature8Title: 'Múltiplas Tags e Filtros',
    aboutFeature8Desc: 'Cadastre músicas com múltiplas tags por vírgula e filtre combinando até 3 tags simultâneas.',
    aboutFeature9Title: 'Reordenação por Arraste',
    aboutFeature9Desc: 'Organize a ordem das músicas no setlist arrastando de forma suave e rápida com física de mola e vibração.',
    aboutFeature10Title: 'Linhas de Anotação e Notas',
    aboutFeature10Desc: 'Adicione avisos, observações ou quebras de seção diretamente no setlist como telas de destaque no Modo Palco.',
    tutorialGuide: 'TUTORIAL PRÁTICO',
    tapForTutorial: 'TOQUE PARA O GUIA',
    stepByStep: 'COMO USAR PASSO A PASSO:',
    proTip: 'DICA DE OURO:',
    understood: 'ENTENDIDO',

    // Sincronização Web
    webEditorTitle: 'WEB EDITOR',
    webSyncSubtitle: 'Conecte ao seu computador via QR Code ou PIN',
    webSyncDesc: 'Transfira todo o seu repertório, letras, cifras e setlists entre o aplicativo do celular e o Web Editor no computador com apenas 1 leitura de câmera ou código PIN de 6 dígitos.',
    openSyncQrBtn: 'ABRIR SINCRONIZADOR QR CODE',

    // Filtros e Tipos de Evento
    filterPrefix: 'FILTRO:',
    filterAll: 'TODAS',
    filterShows: 'SHOWS',
    filterRehearsals: 'ENSAIOS',
    filterRepertoire: 'REPERTÓRIO',
    allPlural: 'TODAS',
    ensaio: 'Ensaio',
    repertório: 'Repertório',
  },

  en: {
    // Navigation & Tabs
    home: 'Home',
    songs: 'Songs',
    setlists: 'Setlists',
    about: 'About',

    // Common Actions & Dialogs
    confirm: 'Confirm',
    cancel: 'Cancel',
    save: 'SAVE',
    close: 'Close',
    closeBtn: 'CLOSE',
    edit: 'Edit',
    delete: 'Delete',
    copy: 'Duplicate',
    share: 'Share',
    exportWord: 'Export Word',
    exportPdf: 'PDF',
    generatingPdf: 'Generating PDF...',
    pdfSuccess: 'PDF created successfully!',
    pdfError: 'Could not generate PDF.',
    exportDocSuccess: 'Document exported successfully!',
    shareTitle: 'Share',
    sharePrompt: 'Choose format:',
    shareAsFile: 'Physical File (.json)',
    shareAsFileDesc: 'Ideal for sending to other app users to import.',
    shareAsText: 'Formatted Text',
    shareAsTextDesc: 'Ideal for sending via WhatsApp, Telegram, etc.',
    shareSuccess: 'Shared successfully!',
    search: 'Search...',
    searchPlaceholder: 'Search...',
    searchPlaceholderDesc: 'Search by title, artist, or style...',
    emptyState: 'No records found.',
    attention: 'Attention',
    success: 'Success',
    info: 'Information',
    optionsBtn: 'Options',
    optionsTitle: 'Options',
    done: 'DONE',

    // Home Tab
    myBands: 'My Bands',
    quickStats: 'QUICK STATISTICS',
    totalSongs: 'Total Songs',
    totalSetlists: 'Total Setlists',
    noBands: 'No bands registered yet. Click "+ Band" at the top to create one!',
    noSongs: 'No songs found. Click "+ Song" at the top to register one!',
    upcomingEvents: 'UPCOMING EVENTS',
    myBandsCarouselSubtitle: 'My Bands (Long press to edit/delete)',
    allBands: 'All Bands',
    showingAllBands: 'Showing all bands',
    showingBandSetlist: 'Showing setlists for',
    showingBandSongs: 'Showing songs for',
    viewAllBands: 'View all bands',

    // Band Management
    addBand: '+ Band',
    newBand: 'NEW BAND',
    editBand: 'EDIT BAND',
    bandNameLabel: 'BAND NAME *',
    coverImageLabel: 'COVER IMAGE (OPTIONAL)',
    imageSelected: 'Image Selected',
    chooseImage: 'Choose Image from Gallery',
    removeImage: 'Remove Image',
    saveChanges: 'SAVE CHANGES',
    createBand: 'CREATE NEW BAND',
    deleteBandConfirmTitle: 'Delete Band',
    deleteBandConfirmMsg: 'Are you sure you want to delete the band "{name}"? Linked setlists will have their band field cleared.',
    deleteBandError: 'Could not delete the band.',
    noBand: 'No Band',

    // Song Management
    addSong: '+ Song',
    newSong: 'NEW SONG',
    editSong: 'EDIT SONG',
    songNameLabel: 'SONG NAME *',
    originalBandLabel: 'ORIGINAL BAND *',
    tagsLabel: 'TAGS ( , )',
    durationLabel: 'DURATION (MM:SS)',
    lyricsLabel: 'Lyrics',
    chordsLabel: 'Chords',
    tabsLabel: 'Tabs',
    lyricsFormLabel: 'Lyrics',
    chordsFormLabel: 'Chords',
    tabsFormLabel: 'Tabs',
    defaultViewLabel: 'DEFAULT VIEW',
    scrollSpeedLabel: 'SCROLL SPEED',
    defaultScrollSpeed: 'DEFAULT SCROLL SPEED (AUTOSCROLL)',
    supportLinks: 'SUPPORT LINKS',
    addLink: 'Add New Link',
    removeLink: 'Remove Link',
    invalidDurationTitle: 'Invalid Duration',
    invalidDurationMsg: 'Please enter duration in MM:SS format (e.g. 03:45) or leave blank.',
    editSongContent: 'EDIT SONG CONTENT',
    disabledLabel: 'Disabled',
    saveSong: 'SAVE SONG',
    alertSongName: 'Please enter the song name.',
    alertOriginalBand: 'Please enter the original band.',
    deleteSongConfirmTitle: 'Delete Song',
    deleteSongConfirmMsg: 'Are you sure you want to delete this song from the global database?',
    deleteSongError: 'Could not delete the song.',
    songAlreadyExists: 'The song "{name}" already exists in the database and was not duplicated.',
    songsBadge: 'songs',
    tagAll: 'All Tags',
    filterByTag: 'Filter by Tag',
    filterByStatus: 'Filter by Status',
    allStatuses: 'All',
    songInfoBpm: 'BPM',
    songInfoCapo: 'Capo',
    songInfoKey: 'Key',

    // Setlist Management
    addSetlist: '+ Setlist',
    newSetlist: 'NEW SETLIST',
    editSetlist: 'EDIT SETLIST',
    presentationType: 'EVENT TYPE',
    show: 'Show',
    rehearsal: 'Rehearsal',
    repertoire: 'Repertoire',
    responsibleBand: 'RESPONSIBLE BAND *',
    registerBandFirst: 'Register at least one band before creating a setlist.',
    setlistNameLabel: 'SETLIST NAME *',
    dateLabel: 'DATE *',
    localLabel: 'LOCATION',
    cachêLabel: 'CACHET ($)',
    notesLabel: 'EVENT NOTES',
    availableSongs: 'AVAILABLE SONGS',
    songsLabel: 'AVAILABLE SONGS',
    reorderBtn: 'REORDER',
    reorderTitle: 'REORDER SETLIST',
    reorderHelp: 'Drag by the ☰ icon to reorder. Tap X to remove.',
    reorderTip: 'Tap a song to select it, then tap another position to move it instantly.',
    reorderTipDrag: 'Drag songs by holding the handle (☰) on the right to reorder smoothly.',
    selectedSongsLabel: 'SELECTED SONGS (DRAG TO REORDER)',
    createSetlist: 'CREATE SETLIST',
    noteItem: 'NOTE',
    notePlaceholder: 'Type notes for this event or performance...',
    alertSetlistName: 'Please enter the setlist name.',
    alertSelectBand: 'Please select an associated band.',
    alertSetlistDate: 'Please enter the setlist date.',
    alertSelectSong: 'Please select at least one song for the setlist.',
    alertSelectSongOrPauseFirst: 'Select a song or pause first.',
    deleteSetlistConfirmTitle: 'Delete Setlist',
    deleteSetlistConfirmMsg: 'Are you sure you want to delete this setlist?',
    deleteSetlistError: 'Could not delete the setlist.',
    addToSetlist: 'ADD TO SETLIST',
    noSongsInSetlist: 'No songs selected for this setlist yet.',
    reorderDoneBtn: 'DONE',

    // Multi-Select Song Picker
    addSongsBtn: 'ADD SONGS',
    selectSongsModalTitle: 'SELECT SONGS',
    selectAll: 'Select All',
    deselectAll: 'Deselect All',
    addSelectedCount: 'ADD SELECTED',
    selectedCount: 'selected',
    noSongsFoundInPicker: 'No songs found.',

    // Setlist Card & Detail Modal
    dateText: 'Date',
    localText: 'Venue',
    cachêText: 'Cachet',
    cacheText: 'Cachet',
    notesText: 'Notes',
    typeText: 'Type',
    songsCount: 'Songs',
    songsTitle: 'SETLIST SONGS',
    estimatedTime: 'Estimated Time',
    venue: 'Venue',
    noSongsInCard: 'No setlists found for active filters.',
    noSongsInDetail: 'No songs associated with this setlist.',
    detailTitle: 'SETLIST DETAILS',
    startStage: 'Stage',
    startStageBtn: 'STAGE MODE',
    setlistTabRepertoire: 'REPERTOIRE',
    setlistTabDetails: 'EVENT DETAILS',
    editNoteTitle: 'EDIT NOTE',
    editPauseTitle: 'EDIT PAUSE',
    tapToEditSongTip: 'Tap song to edit chords/lyrics',
    dragToReorderTip: 'Drag by ☰ icon to reorder',
    swipeToDeleteTip: 'Swipe left to delete',
    rehearsalNotesPlaceholder: 'Rehearsal notes (optional)',

    // Stage Performance Mode
    pause: 'PAUSE',
    pauseTitle: 'PAUSE / BREAK',
    rehearsalReport: 'FULL SETLIST',
    noLyrics: 'No lyrics registered for this song.',
    noChords: 'No chords registered for this song.',
    noTabs: 'No tabs registered for this song.',
    noContentRegistered: 'No content registered for this song.',
    timerCountdown: 'Countdown',
    timerPaused: 'Paused',
    timerFinished: 'PAUSE FINISHED!',
    timerNoLimit: 'NO TIME LIMIT',
    pauseTimer: 'PAUSE TIMER',
    startTimer: 'START TIMER',
    resetTimer: 'RESET',
    closeList: 'CLOSE LIST',

    // Import Modal
    importBtnText: 'Import',
    importTitle: 'IMPORT DATA',
    importTitleSetlist: 'IMPORT SETLIST',
    importTitleSong: 'IMPORT SONG',
    importDescSetlist: 'Select the setlist file (.json) or paste the code in the editor below to import.',
    importDescSong: 'Select the song file (.json) or paste the code in the editor below to import.',
    fileTypeLabelSong: 'song',
    fileTypeLabelSetlist: 'setlist',
    fileTypeLabelBackup: 'backup',
    pasteJsonLabel: 'PASTE JSON CODE HERE',
    importBtn: 'IMPORT DATA',
    importNow: 'IMPORT NOW',
    selectFileLabel: 'SELECT JSON FILE',
    orPasteCode: 'OR PASTE TEXT CODE',
    importSuccessSong: 'Song imported successfully!',
    importSuccessSetlist: 'Setlist imported successfully!',
    importErrorTitle: 'Import Error',
    importErrorMsg: 'Could not import data. Please check JSON formatting.',
    invalidJsonMsg: 'Pasted code is not a valid JSON.',
    fileLoadedAlert: 'File loaded! Click IMPORT NOW to finish.',
    fileReadError: 'Could not read the selected file.',

    // Theme & Appearance
    themeAppearance: 'THEME & APPEARANCE',
    themeMode: 'THEME MODE',
    dark: 'Dark',
    light: 'Light',
    primaryColor: 'PRIMARY COLOR',
    secondaryColor: 'SECONDARY COLOR',
    appLanguage: 'APP LANGUAGE',

    // Backup & Restore
    backupSectionTitle: 'BACKUP & RESTORE',
    backupSubtitle: 'Export or import your entire app database (bands, songs, setlists) safely.',
    backupExportBtn: 'FULL BACKUP (EXPORT)',
    backupImportBtn: 'RESTORE BACKUP (IMPORT)',
    backupExportSuccess: 'Backup exported successfully! File ready to share or save.',
    backupExportError: 'Could not generate backup file.',
    backupImportConfirmTitle: 'Restore Backup',
    backupImportConfirmMsg: 'Choose how you want to restore the backup:\n\n• REPLACE: Completely overwrites existing data with the backup.\n• MERGE: Combines backup data without deleting existing ones.',
    backupImportReplace: 'REPLACE (Overwrite)',
    backupImportMerge: 'MERGE (Combine)',
    backupImportSuccess: 'Backup restored successfully! Database updated.',
    backupImportError: 'Could not restore backup file. Please check file format.',
    backupTipsTitle: 'Backup & Security Tips',
    protectDataLabel: 'How to protect your repertoire data:',
    tip1: '• Do not uninstall to update: To install new updates, simply open the updated APK and install it over the old one. If you uninstall the app completely, the local database will be deleted from the phone by the OS.',
    tip2: '• Make manual backups: Save your most important setlists by generating export codes or JSON files with the share button and keeping them in WhatsApp or notes.',
    tip3: '• Restore data: If you need to reinstall the app or change devices, use the Import option in the corresponding tab and paste the code or select the file to recover everything instantly.',
    backupAllBtn: 'TOTAL BACKUP',
    restoreBackupBtn: 'RESTORE BACKUP',
    restoreBackupTitle: 'RESTORE BACKUP',
    restoreBackupDesc: 'Select the backup file (.json) or paste the code in the editor below to restore all data.',
    backupCreatedAlert: 'Backup created successfully!',
    codeCopied: 'and copied to clipboard!',
    backupAllTitle: 'Total Data Backup',

    // About The App
    loadingDatabase: 'Loading database...',
    aboutTitle: 'ABOUT SETLIST APP',
    aboutHeader: 'ABOUT',
    aboutTheApp: 'The App',
    aboutAppDesc: 'Setlist Band Manager is a professional tool designed to help musicians, bands, and producers organize their repertoire and setlists flawlessly.',
    aboutFeatures: 'Key Features',
    aboutDev: 'DEVELOPED BY:',
    version: 'Version',
    versionText: 'Version',
    developer: 'Developer',
    developedBy: 'Developed with dedication for musicians, bands, and artists.',
    featuresTitle: 'FEATURES',
    feature1: 'Full management of Setlists, Repertoires, and Rehearsals.',
    feature2: 'Stage Performance Mode with auto-scroll and chords.',
    feature3: 'Multi-band support with customized repertoires.',
    feature4: 'Export to Word (.doc), JSON and Full Backup.',
    feature5: 'Full Backup & Restore for total data safety.',
    feature6: 'Support for multiple visual themes and dark mode.',
    aboutFeature1Title: 'Multi-band Management',
    aboutFeature1Desc: 'Register your bands with photo/logo and manage setlists and repertoires for each project.',
    aboutFeature2Title: 'Structured Repertoire',
    aboutFeature2Desc: 'Keep lyrics, chords, tabs, duration, and reference links neatly organized.',
    aboutFeature3Title: 'Stage Mode',
    aboutFeature3Desc: 'View chords and lyrics in full-screen with auto-scroll and dynamic stage marquee.',
    aboutFeature4Title: 'Smart Rehearsals',
    aboutFeature4Desc: 'Rate song performance in rehearsals with colors (green/yellow/red), create notes, and save history.',
    aboutFeature5Title: 'Sharing, Exporting & Backup',
    aboutFeature5Desc: 'Export setlists to Word (.doc), share via JSON, and perform full database backup and restore.',
    aboutFeature6Title: 'Multilingual & Themes',
    aboutFeature6Desc: 'Switch language between Portuguese, English, and Spanish and customize appearance with premium theme colors.',
    aboutFeature7Title: 'Pinned & Favorites',
    aboutFeature7Desc: 'Mark setlists and songs with a star to keep them automatically pinned at the top.',
    aboutFeature8Title: 'Multiple Tags & Filters',
    aboutFeature8Desc: 'Register songs with multiple tags separated by comma and filter combining up to 3 tags simultaneously.',
    aboutFeature9Title: 'Drag-and-Drop Reordering',
    aboutFeature9Desc: 'Reorganize setlist song order by dragging smoothly and quickly with physics and haptic feedback.',
    aboutFeature10Title: 'Setlist Notes & Observations',
    aboutFeature10Desc: 'Add notices, observations, or section breaks inside the setlist, showing as highlight screens in Stage Mode.',
    tutorialGuide: 'PRACTICAL TUTORIAL',
    tapForTutorial: 'TAP FOR GUIDE',
    stepByStep: 'STEP-BY-STEP GUIDE:',
    proTip: 'PRO TIP:',
    understood: 'UNDERSTOOD',

    // Web Sync
    webEditorTitle: 'WEB EDITOR',
    webSyncSubtitle: 'Connect to your computer via QR Code or PIN',
    webSyncDesc: 'Transfer your entire repertoire, lyrics, chords, and setlists between your mobile app and Web Editor on PC using a single camera QR scan or 6-digit PIN code.',
    openSyncQrBtn: 'OPEN QR CODE SYNC',

    // Setlist Filters & Event Types
    filterPrefix: 'FILTER:',
    filterAll: 'ALL',
    filterShows: 'SHOWS',
    filterRehearsals: 'REHEARSALS',
    filterRepertoire: 'REPERTOIRE',
    allPlural: 'ALL',
    ensaio: 'Rehearsal',
    repertório: 'Repertoire',
  },

  es: {
    // Navegación y Pestañas
    home: 'Inicio',
    songs: 'Canciones',
    setlists: 'Setlists',
    about: 'Acerca de',

    // Acciones Generales y Diálogos
    confirm: 'Confirmar',
    cancel: 'Cancelar',
    save: 'GUARDAR',
    close: 'Cerrar',
    closeBtn: 'CERRAR',
    edit: 'Editar',
    delete: 'Eliminar',
    copy: 'Duplicar',
    share: 'Compartir',
    exportWord: 'Exportar Word',
    exportPdf: 'PDF',
    generatingPdf: 'Generando PDF...',
    pdfSuccess: '¡PDF creado con éxito!',
    pdfError: 'No se pudo generar el PDF.',
    exportDocSuccess: '¡Documento exportado con éxito!',
    shareTitle: 'Compartir',
    sharePrompt: 'Elija el formato:',
    shareAsFile: 'Archivo (.json)',
    shareAsFileDesc: 'Ideal para enviar a otros usuarios de la app para importar.',
    shareAsText: 'Texto con Formato',
    shareAsTextDesc: 'Ideal para enviar por WhatsApp, Telegram, etc.',
    shareSuccess: '¡Compartido con éxito!',
    search: 'Buscar...',
    searchPlaceholder: 'Buscar...',
    searchPlaceholderDesc: 'Buscar por título, artista o estilo...',
    emptyState: 'No se encontraron registros.',
    attention: 'Atención',
    success: 'Éxito',
    info: 'Información',
    optionsBtn: 'Opciones',
    optionsTitle: 'Opciones',
    done: 'CONCLUIDO',

    // Pestaña Inicio (Home)
    myBands: 'Mis Bandas',
    quickStats: 'ESTADÍSTICAS RÁPIDAS',
    totalSongs: 'Total de Canciones',
    totalSetlists: 'Total de Setlists',
    noBands: '¡Ninguna banda registrada aún! Haga clic en "+ Banda" arriba para crear una.',
    noSongs: '¡Ninguna canción encontrada! Haga clic en "+ Canción" arriba para registrar una.',
    upcomingEvents: 'PRÓXIMOS EVENTOS',
    myBandsCarouselSubtitle: 'Mis Bandas (Mantén presionado para editar/eliminar)',
    allBands: 'Todas las Bandas',
    showingAllBands: 'Mostrando todas las bandas',
    showingBandSetlist: 'Mostrando setlists de',
    showingBandSongs: 'Mostrando canciones de',
    viewAllBands: 'Ver todas las bandas',

    // Gestión de Bandas
    addBand: '+ Banda',
    newBand: 'NUEVA BANDA',
    editBand: 'EDITAR BANDA',
    bandNameLabel: 'NOMBRE DE LA BANDA *',
    coverImageLabel: 'FOTO DE PORTADA (OPCIONAL)',
    imageSelected: 'Imagen Seleccionada',
    chooseImage: 'Elegir Imagen de la Galería',
    removeImage: 'Eliminar Imagen',
    saveChanges: 'GUARDAR CAMBIOS',
    createBand: 'CREAR NUEVA BANDA',
    deleteBandConfirmTitle: 'Eliminar Banda',
    deleteBandConfirmMsg: '¿Está seguro de que desea eliminar la banda "{name}"? Los setlists vinculados tendrán su campo de banda borrado.',
    deleteBandError: 'No se pudo eliminar la banda.',
    noBand: 'Sin Banda',

    // Gestión de Canciones
    addSong: '+ Canción',
    newSong: 'NUEVA CANCIÓN',
    editSong: 'EDITAR CANCIÓN',
    songNameLabel: 'NOMBRE DE LA CANCIÓN *',
    originalBandLabel: 'BANDA ORIGINAL *',
    tagsLabel: 'ETIQUETAS ( , )',
    durationLabel: 'DURACIÓN (MM:SS)',
    lyricsLabel: 'Letra',
    chordsLabel: 'Acordes',
    tabsLabel: 'Tablatura',
    lyricsFormLabel: 'Letra',
    chordsFormLabel: 'Acordes',
    tabsFormLabel: 'Tablatura',
    defaultViewLabel: 'VISTA PREDETERMINADA',
    scrollSpeedLabel: 'VELOCIDAD DE SCROLL',
    defaultScrollSpeed: 'VELOCIDAD DE DESPLAZAMIENTO PREDETERMINADA (AUTOSCROLL)',
    supportLinks: 'ENLACES DE APOYO',
    addLink: 'Añadir Nuevo Enlace',
    removeLink: 'Eliminar Enlace',
    invalidDurationTitle: 'Duración Inválida',
    invalidDurationMsg: 'Por favor, ingrese la duración en formato MM:SS (ej: 03:45) o deje el campo vacío.',
    editSongContent: 'EDITAR CONTENIDO DE LA CANCIÓN',
    disabledLabel: 'Desactivado',
    saveSong: 'GUARDAR CANCIÓN',
    alertSongName: 'Por favor, introduzca el nombre de la canción.',
    alertOriginalBand: 'Por favor, introduzca la banda original.',
    deleteSongConfirmTitle: 'Eliminar Canción',
    deleteSongConfirmMsg: '¿Está seguro de que desea eliminar esta canción de la base de datos global?',
    deleteSongError: 'No se pudo eliminar la canción.',
    songAlreadyExists: 'La canción "{name}" ya existe en la base de datos y no fue duplicada.',
    songsBadge: 'canc.',
    tagAll: 'Todas las Etiquetas',
    filterByTag: 'Filtrar por Etiqueta',
    filterByStatus: 'Filtrar por Estado',
    allStatuses: 'Todos',
    songInfoBpm: 'BPM',
    songInfoCapo: 'Capo',
    songInfoKey: 'Tono',

    // Gestión de Setlists
    addSetlist: '+ Setlist',
    newSetlist: 'NUEVO SETLIST',
    editSetlist: 'EDITAR SETLIST',
    presentationType: 'TIPO DE EVENTO',
    show: 'Show',
    rehearsal: 'Ensayo',
    repertoire: 'Repertorio',
    responsibleBand: 'BANDA RESPONSABLE *',
    registerBandFirst: '¡Registre al menos una banda antes de crear el setlist!',
    setlistNameLabel: 'NOMBRE DEL SETLIST *',
    dateLabel: 'FECHA *',
    localLabel: 'LUGAR',
    cachêLabel: 'PAGO ($)',
    notesLabel: 'NOTAS DEL EVENTO',
    availableSongs: 'CANCIONES DISPONIBLES',
    songsLabel: 'CANCIONES DISPONIBLES',
    reorderBtn: 'REORDENAR',
    reorderTitle: 'REORDENAR SETLIST',
    reorderHelp: 'Arrastre por el icono ☰ para reordenar. Toque X para eliminar.',
    reorderTip: 'Toca una canción para seleccionarla, luego toca otra posición para moverla instantáneamente.',
    reorderTipDrag: 'Arrastre las canciones sosteniendo el icono (☰) a la derecha para ordenar el setlist suavemente.',
    selectedSongsLabel: 'CANCIONES SELECCIONADAS (ARRASTRE PARA ORDENAR)',
    createSetlist: 'CREAR SETLIST',
    noteItem: 'NOTA',
    notePlaceholder: 'Escriba notas del evento o de la presentación...',
    alertSetlistName: 'Por favor, introduzca el nombre del setlist.',
    alertSelectBand: 'Por favor, seleccione una banda asociada.',
    alertSetlistDate: 'Por favor, introduzca la fecha del setlist.',
    alertSelectSong: 'Por favor, seleccione al menos una canción para el setlist.',
    alertSelectSongOrPauseFirst: 'Seleccione una canción o pausa primero.',
    deleteSetlistConfirmTitle: 'Eliminar Setlist',
    deleteSetlistConfirmMsg: '¿Está seguro de que desea eliminar este setlist?',
    deleteSetlistError: 'No se pudo eliminar el setlist.',
    addToSetlist: 'AÑADIR AL SETLIST',
    noSongsInSetlist: 'Ninguna canción seleccionada para este setlist aún.',
    reorderDoneBtn: 'CONCLUIDO',

    // Selector Múltiple de Canciones
    addSongsBtn: 'AGREGAR CANCIONES',
    selectSongsModalTitle: 'SELECCIONAR CANCIONES',
    selectAll: 'Marcar Todas',
    deselectAll: 'Desmarcar Todas',
    addSelectedCount: 'AGREGAR SELECCIONADAS',
    selectedCount: 'seleccionada(s)',
    noSongsFoundInPicker: 'Ninguna canción encontrada.',

    // Tarjeta de Setlist y Detalles
    dateText: 'Fecha',
    localText: 'Lugar',
    cachêText: 'Pago',
    cacheText: 'Pago',
    notesText: 'Notas',
    typeText: 'Tipo',
    songsCount: 'Canciones',
    songsTitle: 'CANCIONES DEL SETLIST',
    estimatedTime: 'Tiempo Estimado',
    venue: 'Lugar',
    noSongsInCard: 'Ningún setlist encontrado para los filtros activos.',
    noSongsInDetail: 'Ninguna canción asociada a este setlist.',
    detailTitle: 'DETALLES DEL SETLIST',
    startStage: 'Escenario',
    startStageBtn: 'MODO ESCENARIO',
    setlistTabRepertoire: 'REPERTORIO',
    setlistTabDetails: 'DATOS DEL EVENTO',
    editNoteTitle: 'EDITAR NOTA',
    editPauseTitle: 'EDITAR PAUSA',
    tapToEditSongTip: 'Toque en la canción para editar acordes/letra',
    dragToReorderTip: 'Arrastre por el icono ☰ para reordenar',
    swipeToDeleteTip: 'Deslice a la izquierda para eliminar',
    rehearsalNotesPlaceholder: 'Notas del ensayo (opcional)',

    // Modo Escenario (Performance)
    pause: 'PAUSA',
    pauseTitle: 'PAUSA / INTERVALO',
    rehearsalReport: 'SETLIST COMPLETO',
    noLyrics: 'Ninguna letra registrada para esta canción.',
    noChords: 'Ningún acorde registrado para esta canción.',
    noTabs: 'Ninguna tablatura registrada para esta canción.',
    noContentRegistered: 'Ningún contenido registrado para esta canción.',
    timerCountdown: 'Cuenta Regresiva',
    timerPaused: 'Pausado',
    timerFinished: '¡PAUSA FINALIZADA!',
    timerNoLimit: 'SIN LÍMITE DE TIEMPO',
    pauseTimer: 'PAUSAR TEMPORIZADOR',
    startTimer: 'INICIAR TEMPORIZADOR',
    resetTimer: 'REINICIAR',
    closeList: 'CERRAR LISTA',

    // Modal de Importación
    importBtnText: 'Importar',
    importTitle: 'IMPORTAR DATOS',
    importTitleSetlist: 'IMPORTAR SETLIST',
    importTitleSong: 'IMPORTAR CANCIÓN',
    importDescSetlist: 'Seleccione el archivo del setlist (.json) o pegue el código en el editor abajo para importar.',
    importDescSong: 'Seleccione el archivo de la canción (.json) o pegue el código en el editor abajo para importar.',
    fileTypeLabelSong: 'canción',
    fileTypeLabelSetlist: 'setlist',
    fileTypeLabelBackup: 'respaldo',
    pasteJsonLabel: 'PEGAR CÓDIGO JSON AQUÍ',
    importBtn: 'IMPORTAR DATOS',
    importNow: 'IMPORTAR AHORA',
    selectFileLabel: 'SELECCIONAR ARCHIVO JSON',
    orPasteCode: 'O PEGUE EL CÓDIGO DE TEXTO',
    importSuccessSong: '¡Canción importada con éxito!',
    importSuccessSetlist: '¡Setlist importado con éxito!',
    importErrorTitle: 'Error al Importar',
    importErrorMsg: 'No se pudieron importar los datos. Verifique el formato JSON.',
    invalidJsonMsg: 'El código pegado no es un JSON válido.',
    fileLoadedAlert: '¡Archivo cargado! Haga clic en IMPORTAR AHORA para finalizar.',
    fileReadError: 'No se pudo leer el archivo seleccionado.',

    // Tema y Apariencia
    themeAppearance: 'TEMA Y APARIENCIA',
    themeMode: 'MODO DE TEMA',
    dark: 'Oscuro',
    light: 'Claro',
    primaryColor: 'COLOR PRIMARIO',
    secondaryColor: 'COLOR SECUNDARIO',
    appLanguage: 'IDIOMA DE LA APP',

    // Copia de Seguridad y Restauración
    backupSectionTitle: 'COPIA DE SEGURIDAD Y RESTAURACIÓN',
    backupSubtitle: 'Exporte o importe toda la base de datos de la app (bandas, canciones y setlists) con total seguridad.',
    backupExportBtn: 'RESPALDO TOTAL (EXPORTAR)',
    backupImportBtn: 'RESTAURAR RESPALDO (IMPORTAR)',
    backupExportSuccess: '¡Copia de seguridad exportada con éxito! Archivo listo para compartir o guardar.',
    backupExportError: 'No se pudo generar el archivo de copia de seguridad.',
    backupImportConfirmTitle: 'Restaurar Respaldo',
    backupImportConfirmMsg: 'Elija cómo desea restaurar el respaldo:\n\n• REEMPLAZAR: Sobrescribe completamente los datos actuales con la copia de seguridad.\n• FUSIONAR: Combina los datos del respaldo sin eliminar los existentes.',
    backupImportReplace: 'REEMPLAZAR (Sobrescribir)',
    backupImportMerge: 'FUSIONAR (Combinar)',
    backupImportSuccess: '¡Copia de seguridad restaurada con éxito! Base de datos actualizada.',
    backupImportError: 'No se pudo restaurar la copia de seguridad. Verifique el formato del archivo.',
    backupTipsTitle: 'Consejos de Seguridad y Respaldo',
    protectDataLabel: 'Cómo proteger los datos de su repertorio:',
    tip1: '• No desinstale para actualizar: Para instalar nuevas actualizaciones, simplemente abra el APK actualizado e instálelo sobre el antiguo. Si desinstala la aplicación por completo, el sistema operativo borrará la base de datos local del teléfono.',
    tip2: '• Realice copias de seguridad manuales: Guarde sus setlists más importantes generando códigos de exportación o archivos JSON con el botón compartir y guardándolos en WhatsApp o notas.',
    tip3: '• Restaurar datos: Si necesita reinstalar la aplicación o cambiar de dispositivo, use la opción Importar en la pestaña correspondiente y pegue el código o seleccione el archivo para recuperar todo al instante.',
    backupAllBtn: 'RESPALDO TOTAL',
    restoreBackupBtn: 'RESTAURAR RESPALDO',
    restoreBackupTitle: 'RESTAURAR RESPALDO',
    restoreBackupDesc: 'Seleccione el archivo de respaldo (.json) o pegue el código en el editor abajo para restaurar todos los datos.',
    backupCreatedAlert: '¡Respaldo creado con éxito!',
    codeCopied: '¡y copiado al portapapeles!',
    backupAllTitle: 'Respaldo Total de Datos',

    // Acerca de la Aplicación
    loadingDatabase: 'Cargando base de datos...',
    aboutTitle: 'ACERCA DE SETLIST APP',
    aboutHeader: 'ACERCA DE',
    aboutTheApp: 'La Aplicación',
    aboutAppDesc: 'Setlist Band Manager es una herramienta profesional diseñada para ayudar a músicos, bandas y productores a organizar su repertorio y setlists de manera impecable.',
    aboutFeatures: 'Funcionalidades Principales',
    aboutDev: 'DESARROLLADO POR:',
    version: 'Versión',
    versionText: 'Versión',
    developer: 'Desarrollador',
    developedBy: 'Desarrollado con dedicación para músicos, bandas y artistas.',
    featuresTitle: 'FUNCIONALIDADES',
    feature1: 'Gestión completa de Setlists, Repertorios y Ensayos.',
    feature2: 'Modo Escenario con desplazamiento automático y acordes.',
    feature3: 'Soporte multibandas con repertorios personalizados.',
    feature4: 'Exportación a Word (.doc), JSON y Respaldo Total.',
    feature5: 'Copia de seguridad y restauración completa para total seguridad.',
    feature6: 'Soporte para múltiples temas visuales y modo oscuro.',
    aboutFeature1Title: 'Gestión Multibandas',
    aboutFeature1Desc: 'Registre sus bandas con foto/logo y gestione los setlists y repertorios de cada proyecto.',
    aboutFeature2Title: 'Repertorio Estructurado',
    aboutFeature2Desc: 'Guarde letras, acordes, tablaturas, duración y enlaces de apoyo organizadamente.',
    aboutFeature3Title: 'Modo Escenario',
    aboutFeature3Desc: 'Vea acordes y letras en pantalla completa con desplazamiento automático y marquesina dinámica.',
    aboutFeature4Title: 'Ensayos Inteligentes',
    aboutFeature4Desc: 'Evalúe el rendimiento de las canciones en el ensayo con colores (verde/amarillo/rojo), cree observaciones y guarde todo.',
    aboutFeature5Title: 'Compartir, Exportar y Respaldo',
    aboutFeature5Desc: 'Exporte setlists a Word (.doc), comparta en JSON y realice copia de seguridad y restauración total.',
    aboutFeature6Title: 'Soporte Multilingüe y Temas',
    aboutFeature6Desc: 'Cambie entre Portugués, Inglés y Español y personalice el diseño con colores premium.',
    aboutFeature7Title: 'Fijados y Favoritos',
    aboutFeature7Desc: 'Marque setlists y canciones con una estrella para mantenerlos fijados al principio automáticamente.',
    aboutFeature8Title: 'Múltiples Etiquetas & Filtros',
    aboutFeature8Desc: 'Registre canciones con múltiples etiquetas por coma y filtre combinando hasta 3 etiquetas simultáneas.',
    aboutFeature9Title: 'Reordenación por Arrastre',
    aboutFeature9Desc: 'Organice el orden de las canciones en el setlist arrastrando de forma suave y rápida con física de muelle y vibración.',
    aboutFeature10Title: 'Líneas de Anotación y Notas',
    aboutFeature10Desc: 'Agregue avisos, observaciones o saltos de sección directamente en el setlist como pantallas de destaque en el Modo Escenario.',
    tutorialGuide: 'TUTORIAL PRÁCTICO',
    tapForTutorial: 'TOCA PARA LA GUÍA',
    stepByStep: 'CÓMO USAR PASO A PASO:',
    proTip: 'CONSEJO DE ORO:',
    understood: 'ENTENDIDO',

    // Sincronización Web
    webEditorTitle: 'WEB EDITOR',
    webSyncSubtitle: 'Conecte a su computadora mediante código QR o PIN',
    webSyncDesc: 'Transfiera todo su repertorio, letras, acordes y setlists entre la aplicación móvil y el Web Editor en su computadora con solo 1 escaneo de cámara o código PIN de 6 dígitos.',
    openSyncQrBtn: 'ABRIR SINCRONIZADOR QR CODE',

    // Filtros y Tipos de Evento
    filterPrefix: 'FILTRO:',
    filterAll: 'TODAS',
    filterShows: 'SHOWS',
    filterRehearsals: 'ENSAYOS',
    filterRepertoire: 'REPERTORIO',
    allPlural: 'TODAS',
    ensaio: 'Ensayo',
    repertório: 'Repertorio',
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState('en');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function loadLang() {
      try {
        const savedLang = await settingsService.getSetting('appLanguage', 'en');
        setLanguageState(savedLang);
      } catch (error) {
        console.error('Error loading language setting:', error);
      } finally {
        setLoading(false);
      }
    }
    loadLang();
  }, []);

  const setLanguage = async (lang) => {
    setLanguageState(lang);
    await settingsService.setSetting('appLanguage', lang);
  };

  const t = (key) => {
    const langDict = translations[language] || translations.en || translations.pt;
    return langDict[key] || (translations.en && translations.en[key]) || translations.pt[key] || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
        loading
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
